### ISSUE TITLE
Super Darius 2 - Route W boss has no music

### ISSUE THREAD

**Issue by M-Walrus** [MiSTer-devel/TurboGrafx16_MiSTer#100]
There should be a music track for this boss encounter after the initial baby crying sound is played. On MiSTer using the ReDump set, there is no music here.

Confirmed by Rysha/David on original hardware to have music track.

Testing:
The following code will let you go directly to the last stage (also gives you unlimited lives)

Go into configuration menu, highlight the "Silver Hawk Left" option and press Right fifteen times. Then, highlight the "Player" option and press Right fifteen times. Press Run and begin game play. Select any level to start the game with unlimited lives.  
You can't see endings with this code, so it will leave you with the boss if you do a final stage with it, requiring a reset afterwards.

**Comment by sorgelig** [comment]
Should be fixed already

**Comment by M-Walrus** [comment]
confirmed fixed in newest release of core & main.  Thanks sorge!
