### ISSUE TITLE
Darius Plus not loading as *.SGX

### ISSUE THREAD

**Issue by tlaloc-q** [MiSTer-devel/TurboGrafx16_MiSTer#102]
Darius Plus works as a *.PCE file,  but fails to open as a SuperGrafx-enchanced game (my copy of the HuCard image is 786,432 bytes, btw).

According to wikipedia, Darius Alpha & Darius Plus are hybrid PCE/SGX HuCard one-offs that take advantage of the extra capabilities afforded through an SGX, but still remain compatible with the PCE/TGFX16's lesser performance output (at least, on the actual hardware - not that I can verify it ;-)
Can anyone verify if Darius Plus is supposed to take advantage of an SGX's hardware, or is it just Darius Alpha?

**Comment by sorgelig** [comment]
Doesn't work at all or you don't see what you expecting to see?
It works for me in SGX mode without problems.

**Comment by sorgelig** [comment]
Please use forum for discussions. Github is NOT forum!

**Comment by tlaloc-q** [comment]
> 
> 
> Doesn't work at all or you don't see what you expecting to see?
> It works for me in SGX mode without problems.

Doesn't work at all for me, just a black screen.
Funny thing is I place an SGX extension on something like say Paranoia (J) and it plays as SGX ... it's only Darius Alpha.

I apologize if I've misunderstood the purpose of GitHub and thought leaving a comment here was a good a place as any when reporting issues - did not realize there was a separate forum for these types of feedback. Can you please point me to where there is a forum for to do with MiSTer's TGFX16 core's inconsistencies when compared to other implementations/emulations/ACTUAL HARDWARE?

**Comment by sorgelig** [comment]
https://misterfpga.org/viewforum.php?f=19

**Comment by sorgelig** [comment]
All SGX/SGX-enhanced games are well tested and all working.
It's specific to your exact ROM.  So I close this as it's not an issue.
Welcome to forum for generic discussion.
