### ISSUE TITLE
Madden Duo CD Football causes instability

### ISSUE THREAD

**Issue by DeerSteak** [MiSTer-devel/TurboGrafx16_MiSTer#105]
I'm using the Japanese System Card 3.0 BIOS. Just about every game I've tried plays perfectly.

Madden Duo CD Football starts to work. I get as far as the coin toss, and then every time I get that far, the game stops. If I try to switch games without switching cores or rebooting the MiSTer, the next game just loads to a black screen after pressing Run. 

I'm using a Redump image that works correctly in a Super SD System 3 attached to a Core Grafx.

**Comment by sorgelig** [comment]
it hangs on JP BIOS.
Works fine with US BIOS. So use US BIOS for this game.

**Comment by dshadoff** [comment]
Can you check if it still hangs when "CD Seek" is set to "Fast" ?

**Comment by sorgelig** [comment]
Normal/Fast doesn't matter. It always hangs with JP BIOS. 
Looks like incompatibility with JP BIOS. But game is US, so it's possible that exactly US BIOS is required.

**Comment by sorgelig** [comment]
some timing issues has been found and will be fixed in upcoming release

**Comment by sorgelig** [comment]
fixed in today's Main release
