### ISSUE TITLE
Slight graphical glitch: Bakusho Yoshimoto Shinkigeki (SCD)

### ISSUE THREAD

**Issue by Left-Empty** [MiSTer-devel/TurboGrafx16_MiSTer#106]
Greetings,

I encountered a very small graphical glitch in Yoshimoto Shinkigeki.

The second hamburger you can grab, right past the failed rollercoaster jump sequence, is half invisible.

![IMG_0089](https://user-images.githubusercontent.com/62087454/83571301-d12e4700-a527-11ea-983e-730d074043a3.jpg)

Here is footage video I put at the proper time that shows [what it should look like](https://youtu.be/yxIsWQKJp1A?t=310).

Cheers!

**Comment by sorgelig** [comment]
Did you test on real HW? 
Posted video looks like from emulator which may include tweaks like unlimited sprites per line while MiSTer core has limit like real HW.

**Comment by sorgelig** [comment]
I've tested on MiSTer - after other persons left, hamburger became normal. So it looks like HW limitation of sprites per line.

**Comment by Left-Empty** [comment]
Damn that will teach me for looking too hard. I had never noticed it on real hardware, probably because I was just enjoying the moment when I used to play it, instead of looking out for any little glitch!
I'll just test on my console next time, instead of basing myself on wrong memories. Sorry!

**Comment by sorgelig** [comment]
New extra sprite option fixes this problem (which by the way is present on real HW too).

**Comment by Left-Empty** [comment]
Wow, that's awfully nice of you! Thank you very much — and that will prevent me from filling wrong reports of issues :D
