### ISSUE TITLE
Exile II - Janen no Jishou (Japan) - Sound glitch at the end of Riot logo

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/TurboGrafx16_MiSTer#112]
We heard a poke sound at the en of Riot logo at the begining of the game.

I checked on this YT video the poke sound is not present.
https://youtu.be/nJf5sdjqE_E?t=10

**Comment by Left-Empty** [comment]
Can you (or anybody) check on real hardware? I think the person posting those videos is very likely using an emulator (the lack of loading, even on Neogeo Arcade Card game — even a Laser Active experiences some sort of loading on those).
I tried running other Renovation games with that logo on both real hardware and MiSTeR (Browing, Mugensenshi Valis and TenshinoUta), and none of them feature that "pop" sound. It is present on the MiSTer here as well, but I don't own the game to try it out on real hardware.

**Comment by dshadoff** [comment]
The original disc (and the copy I am using on MiSTer) both have a very minor 'pop' at the end of the MiSTer logo, so this is present on original hardware and original disc.

This report discusses something which is - _at best_ - a barely perceptible annoyance, heard once during the game when you start.

Such things should not be reported unless you posses original hardware and can demonstrate a difference (for example with a recording).  Let's not try to invent issues by comparing against sources of unknown origin, or by imagining what we believe the game ought to look like.

**Comment by sorgelig** [comment]
Do not rush to open issue if you are not sure!
Go to forum and ask other users to test on real HW if you can't test yourself.

Compare with youtube where 99% videos are from emulators is unacceptable.

**Comment by wwark** [comment]
Sorry I will post next time on the forum.
Thank you for the check on real hardware.
