### ISSUE TITLE
Dungeon Explorer 2 cutscene videos not working 50% of the time.  

### ISSUE THREAD

**Issue by Bocop** [MiSTer-devel/TurboGrafx16_MiSTer#114]
Depending on the boss, animated intro's to the bosses appear to be corrupted.   Can confirm this happens to more than half as I played through the entire game yesterday on Mister with the latest updates.

**Comment by dshadoff** [comment]
Can you provide a video to indicate what you mean by 'corrupted' ?

Also,
- What version of the core are you running (date, not 'latest')
- is this the USA or Japanese version of the game ?
- please provide a savegame to help the developers reach whatever position is required in order to see this.

**Comment by Bocop** [comment]
Hi David,

Playing the USA version.

Here is a screenshot of what you see during the cutscene on the swamp
witch.

First you see her:

[image: image.png]

Then it goes to her cutscene and you see this:

[image: image.png]

**Comment by Bocop** [comment]
Also the version I used was:  TurboGrafx16_20200618.rbf
<https://github.com/MiSTer-devel/TurboGrafx16_MiSTer/blob/master/releases/TurboGrafx16_20200618.rbf>

And my save file will not allow you to backtrack to the bosses again so
anyone who works on this will just have to play to the first or 2nd boss to
see this.

Thanks,

Joe

**Comment by Left-Empty** [comment]
I tried and couldn't experience the issue on the Japanese version (and boy, are my skills rough at this game!).

There is a password system on the Japanese version. Is it present on the US one too? It might help track the issue — although I've never used it, so I'm unsure how helpful it might be.

**Comment by dshadoff** [comment]
Bocop: I'm afraid that I cannot see the images that you seem to have tried to attach.
Please attach an image to confirm what you mean by corruption (at least one bug has previously been filed, noting behaviour present on original hardware).

As the American release of this game was somewhat rare, it is also possible that the rip you are using could be the source of the issue.

I am also concerned that I will not be able to reach the critical points in the game to confirm; I would need to check twice:
1) Original Hardware & software disc
2) MiSTer with rip from a known source (the original disc used in part 1)

In order to ensure that the developers spend their time on validating and correcting issues, it's important to have savegames (and other means) which help recreate the issue.

**Comment by cr4zymanz0r** [comment]
If we get more details and screenshots/video to know exactly what we're looking for then I can help test. If no savegame/password can be provided before the cutscene, is there at least an estimate of how long I'd have to play to get to the glitch? I can test against original hardware with the original US disc if needed once there's more info.

**Comment by Left-Empty** [comment]
An interesting video I found online:

https://youtu.be/RzEoPSl5BAY?t=363

Is that the glitch you experienced, Bocop? This person is playing using MagicEngine, so that would account for the bad dump theory.

**Comment by Bocop** [comment]
Yes, there is indeed a password system!  Here are the images of the boss
and then what you see when she talks.

This happens about 5-6 times during the campaign, some work, some do not.



Here is a site that has all the secret character passwords that might start
you stronger and in the middle of the game:

https://huguesjohnson.com/guides/de2/characters.html

**Comment by Bocop** [comment]
David,

I appreciate you having a look at this.  I do have 2 different rips and
have had the same thing happen on both but I can try more if need be.

Here is the boss - and then what you see when she talks:

**Comment by Bocop** [comment]
Yes, and mine is even worse as far as how corrupted she is and many of the
other bosses.

Here is what I see:

**Comment by Bocop** [comment]
Here are better images of the Glitch I saw.  Also, Left Empty linked me
this, which is a less but still corrupted image of the cutscene.

https://youtu.be/RzEoPSl5BAY?t=363

You can get to the first few bosses in under an hour for sure.

**Comment by Bocop** [comment]
I'm going to get another dump of the game and test again for you guys, I
would love if that was the issue.


The one I played was: Dungeon Explorer II [U][SCD][TGXCD1034][Hudson
Soft][1993][PCE][thx-1138-darkwater]

**Comment by dshadoff** [comment]
Bocop, I don't know why, but I don't see any attachment or links from you (except the one repeated from Left-Empty).

**Comment by Bocop** [comment]
They are both PNG's?

Here you are again.

**Comment by cr4zymanz0r** [comment]
None of your images are showing up.

**Comment by Bocop** [comment]
[image: image.png]

**Comment by Bocop** [comment]
Holy crap, in all my searching I can only find that dump of the Super CD.
Is that possibly the issue? for years it has been a bad image?

**Comment by dshadoff** [comment]
Possible.  This is why I wanted to replicate before calling it a core issue.

**Comment by Bocop** [comment]
I will keep on searching for a different rip and when I find it, I will
play it.  I used to own this game as well so i am mad at myself for selling
it.  Must preserve gaming history!  :-)

**Comment by Bocop** [comment]
OK, think I found a different rip, the .CUE file seems to be totally
different so does that indicate it is a different rip?

Thanks

**Comment by dshadoff** [comment]
Let's move the back-and-forth conversation to the forums.
GitHub should be used only for adding new information to the issue itself (every developer gets an email for every response here; let's not be annoying).

**Comment by Bocop** [comment]
David,

That sounds great.  I will leave you all with this - I just played through
to the Dark Woods on what appears to be a different rip of the CD and got
the same glitch with the cutscene.

PW right before the Dark Woods boss is:  JGANB-BPAEG-BAGPH-NAAAG-KCAND

You will still probably have to travel west to get to the Dark Woods but at
least you will be at the right place before this boss, as the other ones
have been defeated.

Thanks and I will see you on the forums.

- Joe W.

**Comment by dshadoff** [comment]
Thanks.  With this, I was able to confirm that it:
- does not occur on original console with original disc
- does not occur on MiSTer build with a good rip

Please close this issue.

**Comment by Bocop** [comment]
No I said that I still got the same issue with a different rip.

**Comment by Left-Empty** [comment]
> Thanks. With this, I was able to confirm that it:
> 
>     * does not occur on original console with original disc
> 
>     * does not occur on MiSTer build with a good rip
Mr. Shadoff didn't misread you; what he meant is that he tested a good rip and didn't have the issue. You should look for a proper rip if this glitch annoys you.
Cheers and see you on the forums!

**Comment by Bocop** [comment]
Oh great, so the 2 rips I have are bad.    I will keep hunting for a good
rip, thanks!

**Comment by Bocop** [comment]
@dshadoff  Can you point me in the direction of the rip that works?  or the name of it?  I have tried 3 since and no luck yet on the cutscene that works.

**Comment by dshadoff** [comment]
I did not acquire the image from an internet source, so I won't be able to point you in the direction of such a source.
I ripped it from an original disc that I own.

**Comment by Bocop** [comment]
> I did not acquire the image from an internet source, so I won't be able to point you in the direction of such a source.
> I ripped it from an original disc that I own.

Ah I see.  OK, I will keep looking, thanks again.
