### ISSUE TITLE
Kabuki Itouryodan hangs during data load

### ISSUE THREAD

**Issue by dshadoff** [MiSTer-devel/TurboGrafx16_MiSTer#115]
If you play "versus" mode in Kabuki Itouryodan (Arcade Card fighter game), after selecting characters and handicap, data is loaded, but never stops.

To recreate, use two controllers:
- choose "VS" on title screen
- left character=Kabuki (default), right character=Kabuki (default)
- handicap screen, press RUN (default settings)
...the system will try to load data, and will hang (the "Disk" LED will remain on)

**Comment by Left-Empty** [comment]
This won't happen if you choose a different stage than the default one (Kabuki Danjuro's, depicted below) in VS mode. It will still happen in single player when that stage loads.

![Kabuki Ittouryoudan (Japan) 2020-07-01 00 38 07](https://user-images.githubusercontent.com/62087454/86184104-b99cab00-bb33-11ea-8613-f14bf52adf9f.png)

**Comment by dshadoff** [comment]
Fixed in newest release of Main-MiSTer.  Closing
