### ISSUE TITLE
PC Engine CD - Bomberman: Panic Bomber: Game freezes randomly in story mode at round start. 

### ISSUE THREAD

**Issue by M-Walrus** [MiSTer-devel/TurboGrafx16_MiSTer#120]
Using Super CD-ROM System (Japan) (v3.0) BIOS

Happens in both redump versions of Bomberman: Panic Bomber - (FAAT) and (FABT) 
In the (FABT) version I had this happen repeatedly at the start of the second round in story mode. 
The (FAAT) version seems more stable, and the freezing is a bit more random (can happen at the start of any stage)

Here is a video of it happening at the start of the 3rd round on the (FAAT) version:
https://youtu.be/_Eo2ppPr6c4

I've never seen it freeze on the first round- most often it's occurred on round two or three, always at the start of the round just after the stage music begins to play.

**Comment by dshadoff** [comment]
I was also able to recreate this on the most recent core, as well as the release from June.
It's inconsistent - I saw it happen once out of four times on Stage 2 for example (even after a loss "continue").

Looks like it might be a race condition of some sort; the CD music starts, but the stage doesn't start playing.

**Comment by dshadoff** [comment]
Fix was applied to Main-MiSTer, and seems to fix the problem as far as I can see.
Will be generally available with next release of Main-MiSTer (relatively frequent).

**Comment by M-Walrus** [comment]
Re-opening this ticket as the issue seems to be happening again. Like before, this seems most common in the FABT version.

**Comment by birdybro** [comment]
https://www.youtube.com/watch?v=Z94nNmx2fmA - vid with debug console open.

Failure:
```
PCECD: Command SAPSP, start = 15190, end = 255495, [1] = 00, [2] = 03, [9] = 80
PCECD: Command SAPEP, end = 24649, [1] = 01, [2] = 04, [9] = 80
PCECD: Command undefined, [0] = FF, [1] = FF, [2] = FF, [3] = FF, [4] = FF, [5] = FF
```

Success also included the undefined command, however it continued after a pause in lba:

```
PCECD: Command SAPSP, start = 15190, end = 255495, [1] = 00, [2] = 03, [9] = 80
PCECD: Command SAPEP, end = 24649, [1] = 01, [2] = 04, [9] = 80
PCECD: Command undefined, [0] = FF, [1] = FF, [2] = FF, [3] = FF, [4] = FF, [5] = FF
PCECD: Command PAUSE, current lba = 15195
From sector 15195 to sector 15190:
Time = 393.11 milliseconds
seek time ticks: 29
PCECD: Command SAPSP, start = 15190, end = 255495, [1] = 00, [2] = 03, [9] = 80
PCECD: Command SAPEP, end = 24649, [1] = 01, [2] = 04, [9] = 80
```

**Comment by birdybro** [comment]
Confirmed with @dshadoff 's latest commit that this seems to fix the issue. When a new binary for Main is released, that should resolve this.

https://github.com/MiSTer-devel/Main_MiSTer/commit/b12ff264a24713278e78302ede1c32578499d938

**Comment by M-Walrus** [comment]
Played through to 3rd stage on FAAT and FABT versions several times and did not encounter any freezes. Closing this ticket.
