### ISSUE TITLE
Latest version looses sync with my TV...

### ISSUE THREAD

**Issue by bootsector** [MiSTer-devel/TurboGrafx16_MiSTer#121]
... and now I've got only a NO SIGNAL screen. :(

**Comment by dshadoff** [comment]
Perhaps you could describe your TV in some way.
(HDMI ?  RGB ?  What resolution and settings ?  Any scalers in use ?)

Also, if you go back and try the previous version of the core again, does it work, or is the same thing happening on that version as well ?

**Comment by bootsector** [comment]
Hmmm... previous version stopped working as well. Maybe something changed in the framework?

I'm using direct HDMI connection to my Samsung TU8000 4K TV.

Settings are:

```
video_mode=8
vsync_adjust=2
```

**Comment by bootsector** [comment]
Ok. It turned out to be a bad HDMI cable connection. Strangely that affected only the TG16 core. Problem solved! Thank you!
