### ISSUE TITLE
Incorrect colors on title screen in Space Ava 201 in SuperGrafx mode

### ISSUE THREAD

**Issue by TheOpponent** [MiSTer-devel/TurboGrafx16_MiSTer#124]
The developer posted direct captures of the game's title screen at https://twitter.com/nicole_express/status/1326655380160712707

The current MiSTer core does not reproduce the silhouette correctly with or without the Arcade Card installed.

No Arcade Card, original colors:
![NODATE-screen_0015](https://user-images.githubusercontent.com/8432212/98881654-86124b80-2458-11eb-8ffc-14a61e87a52a.png)

No Arcade Card, raw RGB:
![NODATE-screen_0016](https://user-images.githubusercontent.com/8432212/98881658-8874a580-2458-11eb-9bc9-ae293e4e1422.png)

Arcade Card, original colors:
![NODATE-screen_0017](https://user-images.githubusercontent.com/8432212/98881661-8a3e6900-2458-11eb-9668-518e72e15407.png)

Arcade Card, raw RGB:
![NODATE-screen_0018](https://user-images.githubusercontent.com/8432212/98881666-8b6f9600-2458-11eb-96b9-dd3ca7902388.png)

**Comment by nicolebranagan** [comment]
Hello; I'm the developer in question, please let me know if there's more information I can provide. The source for the title screen is here https://github.com/nicolebranagan/spaceava201/blob/master/src/title/title.c I'm expecting background palette color 0 to be the background here.

**Comment by sorgelig** [comment]
> Hello; I'm the developer in question

Nice to see you here!
Supposed to be fixed in new release.

**Comment by TheOpponent** [comment]
Colors in 20201113 build now look much closer to the reference captures:

![NODATE-screen_0020](https://user-images.githubusercontent.com/8432212/98995929-16579b80-2500-11eb-964c-5ea7bb874010.png)
![NODATE-screen_0021](https://user-images.githubusercontent.com/8432212/98995930-16f03200-2500-11eb-8491-48768957fec1.png)
![NODATE-screen_0023](https://user-images.githubusercontent.com/8432212/98995932-18215f00-2500-11eb-856f-909ef4cb0f99.png)
![NODATE-screen_0024](https://user-images.githubusercontent.com/8432212/98995938-19528c00-2500-11eb-974a-9e04511153b4.png)

Thank you for your quick response.

**Comment by nicolebranagan** [comment]
Looks good to me! I would not take my screenshots as color gospel, as none of my equipment is calibrated.

**Comment by sorgelig** [comment]
colors are highly depend on applied gamma correction as well.

**Comment by MatsuMatsu87** [comment]
mmmmm, strange. Just checked this game on mister, and have no luck getting the correct colors.
Neither build 20201113 which supposedly works or the current 20210225.
