### ISSUE TITLE
Last Armageddon - graphical issue

### ISSUE THREAD

**Issue by dshadoff** [MiSTer-devel/TurboGrafx16_MiSTer#127]
Start a new game:
- Wait for the title screen, press run button at the prompt;
- Skip the intro sequence by holding the II button;
- Start a new game (first option) at the menu;
- Travel downward slightly, to get out of the stone circle;
- Hold down the I button to skip time until an encounter happens;
- Press I to resolve the fight automatically;
- Walk a little to the south and east; the coastline should appear, along with glitches.

After a fight, the borders of some of the coastline are changed to parts of the ideograms used to signal an encounter ("獲物がいたぜ！").

See this thread:
[https://misterfpga.org/viewtopic.php?f=19&t=1530&p=12960#p12960](url)

**Comment by wwark** [comment]
Below url working.
https://misterfpga.org/viewtopic.php?f=19&t=1530

**Comment by dshadoff** [comment]
Seems to be related to a VRAM transfer not happening as expected - either the tiles or the background attribute table.
Could be very small issue with timing of interrupt or something like that.
I think this may need the help of srg320 or sorgelig to solve.

**Comment by Left-Empty** [comment]
I do not know if this might have any influence, but the core switches pretty often between 360x242 and 270x242 resolutions. It does it everytime there is an event or fullscreen graphics. It doesn't do it between the world map and fights though.

**Comment by dshadoff** [comment]
New release came out today, fixing this.
I was not able to reproduce.
Closing issue.
