### ISSUE TITLE
TGFX CD - Jack Nicklaus Turbo Golf (USA) - Intro/Title video and audio skipping

### ISSUE THREAD

**Issue by M-Walrus** [MiSTer-devel/TurboGrafx16_MiSTer#129]
Turbografx CD - Jack Nicklaus Turbo Golf (USA) from the most recent ReDump set tested by multiple people with this issue.

On the title screen the music is skipping, but it's also making the MiSTer menu unresponsive while the skipping is happening.

The issue clears up when the demo loop starts or a game starts. Issue only seems to occur at the initial title screen.

**Comment by Left-Empty** [comment]
Same behaviour happening on the Japanese version (Jack Nicklaus' World Tour Golf) of the game.
What a strange one!

**Comment by sorgelig** [comment]
will be fixed in next release of Main.

**Comment by dshadoff** [comment]
Should be in latest release from today.  Please update, test and close.
(It's working for me now)

**Comment by M-Walrus** [comment]
Issue is confirmed fixed by multiple users, and is working on my side as well.  Closing this issue out.
