### ISSUE TITLE
PCE-CD game - Black Hole Assault - Glitched cutscenes

### ISSUE THREAD

**Issue by Hewhoisred** [MiSTer-devel/TurboGrafx16_MiSTer#131]
Opening cutscene:
![blackholeassault](https://user-images.githubusercontent.com/47957258/102716393-788a8580-4290-11eb-8909-00a6bfae7cdf.gif)

Comparison video, found on youtube:
https://youtu.be/4Virk0HXo0M?t=48

Tested on 20201220 rbf.

The problem seems to appear in all cutscenes, not just the opening intro.

**Comment by dshadoff** [comment]
I was not able to recreate this issue.
I am using a BIN+CUE rip from a CDROM in my personal collection.

I tried the following versions:
20201117 - previous official build
20201219 (*) - local build, including srg320's change from Friday
20201220 - today's official build

I am inclined to think that this is related to your game image; have you tested with the previous version of the core ?
And where did you get your image ?

**Comment by Hewhoisred** [comment]
I tried it with the most recent build and the build before.  I will seek out another bin+cue and confirm the issue.

**Comment by srg320** [comment]
This issue occurs if selected "Sprites per line: Extra", try with "Normal".

**Comment by Hewhoisred** [comment]
Ah, thank you.  Closing.
