### ISSUE TITLE
Tenshi no Uta II: Failure to load after FMV and when leaving town immediately

### ISSUE THREAD

**Issue by CollectiveSouls** [MiSTer-devel/TurboGrafx16_MiSTer#133]
Core Version: 20201220 (also occurs in 20201117 & 20200922)
Bios used: PCE SuperCDROM 3.0
---------------------------------------------------
//Hardware Settings//
Rom Data Swap: No
~~
Arcade Card: Enabled (also occurs disabled)
CD Seek: Normal
User I/O: Off
MB128: Disabled

//Audio and Video///
Aspect Ratio: Original
Scandoubler fx: None
--
Colors: Original
Overscan: hidden
Border Color: Original
Sprites per Line: Normal
--
CD Audio boost: No
Master Audio Boost: No
-------------------------------------------------
Issue: If you enter any town or dungeon and immediately leave before the CD audio starts playing(holding down when entering from the world map), the game will crash. There is also a part of the game where you enter a town and a cutscene plays. Then when it is finished it will show you back on the world map and then it will try and load the town as if you were entering it normally. It shows the town name on screen like usual but fails to load the town and locks up. 

Other than this the game does work as it should. There is also a cutscene which occurs in the first dungeon while you're in it and it does not lead to the game crashing.

I've included 2 log files and save data. You can load either and leave and reenter the town that you're in, then hold down to reproduce the town crash. I can also explain the process for the cutscene crash if anyone would like to reproduce that as well.

Files inside Zip
//Log File: Mister_PCECD_TnU2.log//
Shows the log for the cutscene crash

//Log File: Mister_PCECD_TnU2T.log///
Shows the log for the leaving town immediately crash

//File: Tenshi no Uta II - Datenshi no Sentaku.sav//
Save file for game

[TnU2Logs+save.zip](https://github.com/MiSTer-devel/TurboGrafx16_MiSTer/files/5753143/TnU2Logs%2Bsave.zip)

**Comment by dshadoff** [comment]
I have verified that the "exit + re-enter + quickly exit" error is real, and does NOT happen on the actual hardware.
I suspect that this issue may related to issuing a new CDROM command while the previous command is still processing... or something like that.


Can you give details on the cutscene crash, so I can understand if it is similar or a different mechanism ?

**Comment by CollectiveSouls** [comment]
Sure can. 
-  Load the Lvl10 save game (savegame 2) and leave town.
- Open the menu by pressing I, press down once to select the item inventory 道具.
- In the inventory select use (便う) and select the bell(リモンの鈴) on page 2 which will let you teleport to any previously visited town
- select オアシスのラハーサ
- Enter town for cutscene. Pressing select skips the cutscene. Crash happens both skipped or not.

**Comment by dshadoff** [comment]
Yes, that's also a real one, and it happened without me pressing any buttons.
Not sure if the problem is within the Main_MiSTer, fetching the data, or in the core just afterward...

**Comment by dshadoff** [comment]
Update - this is related to CD command sequence during head seek.  If you play the game with "CD = Fast", the "exit + re-enter + quickly exit" issue will not occur.

**Here is a data log with "CD Seek = Fast", compared with the same sequence with "CD Seek = Normal".  Note the line in bold on each, which is different.**

```
PCECD: Command SAPSP, start = 16823, end = 224023, [1] = 00, [2] = 04, [9] = 80
PCECD: Command SAPEP, end = 25895, [1] = 01, [2] = 05, [9] = 80
seek time ticks: 0
PCECD: Command READ6, lba = 4168, cnt = 78
seek time ticks: 0
PCECD: Command SAPSP, start = 25895, end = 224023, [1] = 00, [2] = 05, [9] = 80
**PCECD: Command SAPEP, end = 30484, [1] = 01, [2] = 06, [9] = 80**
seek time ticks: 0
PCECD: Command READ6, lba = 3880, cnt = 96
seek time ticks: 0
```


**Same sequence, with "CD Seek = Normal":**

```
PCECD: Command SAPSP, start = 16823, end = 224023, [1] = 00, [2] = 04, [9] = 80
PCECD: Command SAPEP, end = 25895, [1] = 01, [2] = 05, [9] = 80
Switch to core frame buffer
From sector 18008 to sector 4168:
Time = 725.69 milliseconds
seek time ticks: 54
PCECD: Command READ6, lba = 4168, cnt = 78
From sector 4246 to sector 25895:
Time = 792.93 milliseconds
seek time ticks: 59
PCECD: Command SAPSP, start = 25895, end = 224023, [1] = 00, [2] = 05, [9] = 80
**PCECD: Command undefined, [0] = FF, [1] = FF, [2] = FF, [3] = FF, [4] = FF, [5] = FF**
From sector 25895 to sector 3880:
Time = 789.42 milliseconds
seek time ticks: 59
PCECD: Command READ6, lba = 3880, cnt = 96
```

The SAPEP command is not formed correctly in the second case; it may rely on a return code (or timing of the returned data) in order to prepare the SAPEP request.

**Comment by dshadoff** [comment]
I have isolated the issue, but I'm not sure why the code was written this way... so I'm not sure if it will break something.

Looking for guidance from @sorgelig and @srg320 :
In Main_MiSTer, in support/pcecd/pcecd.cpp, line 37 says:

```
		if (pcecdd.has_status && !pcecdd.latency) {
			pcecdd.SendStatus(pcecdd.GetStatus());
			pcecdd.has_status = 0;
		}
		else if (pcecdd.data_req) {
			pcecdd.SendDataRequest();
			pcecdd.data_req = false;
		}
```

This has the effect of only sending status (i.e. acknowledgement of the command) back to the core if the command has no head seek.  (I'm not sure when status is confirmed in such a case.).  From the log above, it appears that the game is expecting acknowledgement sooner, and the following message is problematic as a result.

Changing the first line to this will fix the problem for Tenshi no Uta II, without appearing to break:
`		if (pcecdd.has_status) {`

...However, it's not clear to me yet whether this causes any harm.
I would like to hear whether the original authors agree with this fix.

**Comment by dshadoff** [comment]
A fix has been made to Main_MiSTer, and a new release published.
Please retest, and if this fixes your problem please close this issue.

**Comment by CollectiveSouls** [comment]
Tenshi no Uta 2 fully works and no other problems were added with the fix. Thanks for the work Srg and Shadoff.
