### ISSUE TITLE
Certain game files showing "LOAD ERROR!"

### ISSUE THREAD

**Issue by edrozenberg** [MiSTer-devel/TurboGrafx16_MiSTer#134]
I've come across certain titles that don't load, showing `LOAD ERROR!`. Using JPN Super CD v3.0 BIOS.

For the ones showing error I did compare checksums with the source, and they are correct - no download issue on my end. No isssue with the CUE files, img name in the CUE is correct.

These same titles load with NO problem on OpenEmu for MacOS using the same BIOS version.

Maybe there's some small tweak that's required for some of these titles to load in MiSTER, not sure.

My workaround for MiSTER for now is to use a different version of the problem games from a different source - was able to find versions that work fine in MiSTER. Still it's interesting that some files that load in OpenEmu do not load in MiSTER.

**Comment by dshadoff** [comment]
I haven't seen any issues like this... what file type(s) were they ?
Was there log output during the initial load of the CUE file which might have hinted at an error ?
Post a copy of an example CUE here.  It might be an unsupported type or something.

**Comment by edrozenberg** [comment]
One example of a problem:
`Puyo Puyo CD (SCD)(JPN)` from **TGFX16-CD/PCE-CD Organized set**.

Redownloaded, recopied, and retested the title just now and:
1. Loads OK in OpenEmu MacOS
2. Load error in MiSTER

Same issue with quite a few other titles from that same set under MiSTER. Some work, many don't.

Test files:
```
# find /media/fat/games/TGFX16-CD/New/Puyo\ Puyo\ CD\ \(SCD\)\(JPN\)/
/media/fat/games/TGFX16-CD/New/Puyo Puyo CD (SCD)(JPN)/
/media/fat/games/TGFX16-CD/New/Puyo Puyo CD (SCD)(JPN)/Puyo Puyo CD (SCD)(JPN).bin
/media/fat/games/TGFX16-CD/New/Puyo Puyo CD (SCD)(JPN)/Puyo Puyo CD (SCD)(JPN).cue
```

CUE file contents:
```
FILE "Puyo Puyo CD (SCD)(JPN).bin" BINARY
  TRACK 01 AUDIO
    INDEX 01 00:00:00
  TRACK 02 MODE1/2048
    PREGAP 00:03:00
    INDEX 01 01:51:35
  TRACK 03 AUDIO
    PREGAP 00:02:00
    INDEX 01 03:19:35
  TRACK 04 AUDIO
    INDEX 01 06:49:01
  TRACK 05 AUDIO
    INDEX 01 07:25:32
  TRACK 06 AUDIO
    INDEX 01 07:50:24
  TRACK 07 AUDIO
    INDEX 01 08:17:61
  TRACK 08 AUDIO
    INDEX 01 08:48:07
  TRACK 09 AUDIO
    INDEX 01 09:31:57
  TRACK 10 AUDIO
    INDEX 01 09:52:15
  TRACK 11 AUDIO
    INDEX 01 10:17:21
  TRACK 12 AUDIO
    INDEX 01 10:45:53
  TRACK 13 AUDIO
    INDEX 01 11:21:56
  TRACK 14 AUDIO
    INDEX 01 11:43:23
  TRACK 15 AUDIO
    INDEX 01 12:22:10
  TRACK 16 AUDIO
    INDEX 01 12:45:69
  TRACK 17 AUDIO
    INDEX 01 13:14:40
  TRACK 18 AUDIO
    INDEX 01 13:45:42
  TRACK 19 AUDIO
    INDEX 01 14:08:17
  TRACK 20 AUDIO
    INDEX 01 14:33:51
  TRACK 21 AUDIO
    INDEX 01 15:02:36
  TRACK 22 AUDIO
    INDEX 01 15:36:08
  TRACK 23 AUDIO
    INDEX 01 16:17:26
  TRACK 24 AUDIO
    INDEX 01 17:02:23
  TRACK 25 AUDIO
    INDEX 01 17:40:02
  TRACK 26 AUDIO
    INDEX 01 18:38:55
  TRACK 27 AUDIO
    INDEX 01 19:11:60
  TRACK 28 AUDIO
    INDEX 01 19:57:38
  TRACK 29 AUDIO
    INDEX 01 20:32:05
  TRACK 30 AUDIO
    INDEX 01 21:28:55
  TRACK 31 AUDIO
    INDEX 01 22:35:04
  TRACK 32 AUDIO
    INDEX 01 23:17:59
  TRACK 33 AUDIO
    INDEX 01 23:35:19
  TRACK 34 AUDIO
    INDEX 01 27:04:18
  TRACK 35 AUDIO
    INDEX 01 30:57:20
  TRACK 36 AUDIO
    INDEX 01 34:37:25
  TRACK 37 MODE1/2048
    PREGAP 00:03:00
    INDEX 01 40:05:22
```

**Comment by dshadoff** [comment]
That does not look like a well-formed CUE/BIN set.
A unified BIN file would not intermingle 2352-byte sectors (i.e. AUDIO) with 2048-byte MODE1 sectors in the same large .bin file (although 2352-byte MODE1 would be fair game).

I would say to stay away from files from that source... and you seem to have found another source that works, so I don't think this is a problem.

**Comment by edrozenberg** [comment]
OK thanks.
