### ISSUE TITLE
Support for patched roms

### ISSUE THREAD

**Issue by thehughhefner** [MiSTer-devel/TurboGrafx16_MiSTer#136]
Hi,
There are some patched roms that are in TOC and CUE format and also some audio being in ISO and WAV.  If we take a look at the Cotton remastered, there seems to be a toc file, a cue file, a wav file, and also two tracks being in iso. Is there a possibility of adding support for patched roms?  

Kind regards

**Comment by dshadoff** [comment]
First, I wouldn't refer to CUE+ISO_WAV images as ROMs... rather, they are images of CDROMs.
Also, the CUE+ISO+WAV format is already supported, for CD-type images.

I'm not clear on your question about "patched roms"...

For ROMs - or CDROM images - which have already had patches applied, they are run the same as be any other unpatched image. Occasionally, such patches have been known introduce bugs into the game itself, or to be dependent on a specific emulator - so be careful about assuming these to be 100% operational.

If you are asking about applying patches at the time of loading, this is not currently supported, and would not be easy to implement - there are simply too many patching formats to support, as well as difficulties including this in the user interface.  And there is already a cheat system in place which may complicate matters.

It's up to Sorgelig, but my assessment is that this is a high-effort/low-payback feature request.

**Comment by sorgelig** [comment]
I don't understand what OP wants, actually.. CUE with mixed WAV/BIN/ISO files is supported already. TOC i think has no use.

**Comment by thehughhefner** [comment]
Hi,

There seems to be some misunderstanding from my side. I thought the PCE core didnt support WAV and ISO files, let alone patched ROMs. Wiki needs to be updated.  I will close this ticket. Thank you for the information and keep up the good work
