### ISSUE TITLE
Video info not showing up

### ISSUE THREAD

**Issue by type78** [MiSTer-devel/TurboGrafx16_MiSTer#140]
This core is not showing any video info up even with option, 'video_info=10' in 'mister.ini'. 
(20210225 release)

**Comment by sorgelig** [comment]
Cannot confirm this. It always shows for me.

**Comment by evidencedj** [comment]
I know it is already closed. Is there an easy solution for this "issue"? I have got the same problem. The video info only shows if I change from TurboGrafx to Supergrafx. If I start any TurboGrafx Rom, no video info will be available. I have deleted my TurboGrafx config file and in addition to that I have reset all settings. No success in showing the video info.

**Comment by sorgelig** [comment]
info will be shown only if video parameters are changed. If games use the same resolution then info might not be shown.
