### ISSUE TITLE
Devil's Crush Ball physics / sticky flipper

### ISSUE THREAD

**Issue by 0x41726C6F** [MiSTer-devel/TurboGrafx16_MiSTer#141]
I’ve noticed some odd physics issues in Devil’s Crush wherein the ball “sticks” to the flipper, or leaves the flipper in an odd way. Here is a [~1 minutes YouTube video](https://youtu.be/DcAHn_ic7AQ) from a recent play session. The 5+ times it happened were over two games. The issue occurs more often (or is more obvious) with the Ball Speed set to Slow, but it happens with both Slow and Fast ball speed. I have played entire games without noticing the issue, but it’s rare. A normal game for me is ~30 minutes. 
So far I’ve; 
Run the “Update All” script. 
Tried various revisions of the Core, rolling back to a version from a year ago etc.
Checked the MD5 of the ROM (92FBE89D4C87BF283DBFBEAC69A64E6E) on the SD card and it checks out.  
Tested the Memory module (128 MB) with the memtest utility on Auto (after an hour it shows 142Mhz no errors)
Replaced the SD card in the DE10 Nano, reinstalling everything. 
Reset the controller(s) trying both wired (the TurboGrafx Mini USB) and Wireless (the 8BitDo SN30).
Cleared all settings F12 menu.
Played on a HDMI/DVI monitor and Sony PMV via RGB. 

I don’t have original hardware to test on, so maybe this is normal? 

If there is anything else I can test/provide let me know. 

Thanks for everything.

**Comment by Left-Empty** [comment]
I'm "happy" to reply this seems consistant with the behaviour on a real machine with an original HuCard.

This game was a favourite of my dad, and he never complained about it. He was playing on Fast Ball exclusively.

I just played the game for over an hour, on slow, and while I couldn't have the glitch display _just as_ you recorded it, even when though it was happening faster, I could tell that what I thought then were my errors and seemed to be just my mishandling of the ball by trying to be too greedy with my flipper is instead a glitch of sort, and the one you recorded. A couple of instances were really me kicking the ball full speed and it seemingly teleporting back to the drain, given the speed — and that was on Slow Ball speed.
This being already tough to compute on that speed, I can only guess it may be near invisible on Fast Ball setting.

I couldn't help, playing after so many years, to notice how the "physics" seem to be take on different rules around the players flippers. One that would akin to magnets messing around in modern pinball. It was probably to make it less probably for the ball to drain or get stuck?

That was an interesting travel back in time in any case. And what a good game!
I'd love for others to chime in before closing this, as in my case, it all happened at such fast speed it was tough to be sure. I actually had to have it happen multiple times succeedingly for me to really come to the sense it was most likely the same twisty glitch happening.
Also thanks for the video, that made it super easy to understand the issue.

**Comment by dshadoff** [comment]
The original description made on the forum sounded a lot more serious than the video showed.  What I saw on the video was characteristic of what I have seen while playing the game on real hardware (both Alien Crush and Devil's Crush).

While a pinball simulator was a nice idea in the late 80s, I don't think it ever took itself seriously enough to try to be ultra-realistic in terms of game play... that type of pinball simulator was popularized in the following generation (or two) of consoles, where more compute power was available.

The other reason I don't consider this to be an issue with the core, is that I can't imagine any mechanism of failure which would affect this game alone, in such a subtle manner, without causing huge issues across other titles with respect to controls.

**Comment by 0x41726C6F** [comment]
Just to be clear, I am not seeing a similar physics issue in Alien Crush. I'll play it more in the next day or two (no great burden), but I've never seen anything similar in Alien Crush, or Devil's Crash MD for the Genesis. Seeing an Alien Crush predated Devil's Crush, I would expect the physics to be on-par or better. 
If you watch the video at ~45 seconds in the ball takes a 90 degree turn and looks to accelerate across the board. I couldn't easily figure out how to slow the video down when I upload it to YouTube, but you can watch it a 1/4 speed in the Youtube settings and it's easier to see. 
I agree it seem odd it would only effect one game, I've never had any other issues (that I could detect) on other TG16 games. I bought a FGPA book, that does not seem to be sufficient, I might have to read it.... 
Down the road I might buy original hardware, or more likely the Analogue Duo/Pocket, which would be another sample if nothing else.
