### ISSUE TITLE
Soldier Blade SFX volume too low VS music.

### ISSUE THREAD

**Issue by pixeltao** [MiSTer-devel/TurboGrafx16_MiSTer#142]
When playing Soldier Blade, the sounds effects appear very subdued compared to the music volume. I did a comparison with the game on a Turbo Everdrive on real hardware and the SFX appears to be mixed louder with the music compared to the game played on MiSTer.

That said, I did not notice that difference as much with other games. This is maybe because, even on real hardware, the SFX in Soldier Blade are mixed rather low with the music. Maybe this difference is amplified on MiSTer, making it more noticeable.

**Comment by SegaSnatcher** [comment]
All the videos I've seen on youtube seem pretty consistent with music being noticeably louder than sound effects.  The videos seem to be a mix of people running emulators and some real hardware, but it seems rather consistent with the music being louder.

https://www.youtube.com/watch?v=B64FY3i1IA8

**Comment by pixeltao** [comment]
> All the videos I've seen on youtube seem pretty consistent with music being noticeably louder than sound effects. The videos seem to be a mix of people running emulators and some real hardware, but it seems rather consistent with the music being louder.
> 
> https://www.youtube.com/watch?v=B64FY3i1IA8

Yeah, the music is definitely louder than the SFX even on real hardware. It's not the issue. The issue is that on the MiSTer, the SFX sound even lower than on real hardware compared to the music.

For example, when played on MiSTer, you can barely hear the enemy explosions: the music covers the sound too much. But on real hardware, I can hear those explosions clearly, even if the music is noticeably louder.

Definitely a minor issue though. I had to compare by switching back and forth between the MiSTer and my TGFX16 to confirm the difference.

**Comment by sorgelig** [comment]
make sure you don't use any audio booster options in menu.

**Comment by pixeltao** [comment]
This sounded like a good lead, but even with all audio booster disabled, this PSG channel sounds too quiet on MiSTer when compared to the game running on a TG16. Maybe I'm crazy, no one else seem to notice this issue.

**Comment by sorgelig** [comment]
Probably it's subjective. May be it's related to filtering or something other post-processing.

**Comment by birdybro** [comment]
Hi @pixeltao can you provide a recording off of your original hardware you are comparing to and provide some info about the hardware like the model, hopefully serial number or motherboard revision, etc...?

https://tcrf.net/Super_Star_Soldier

Go into the hidden sound test menu here. And play the first 9 sound effects in a row in your recording.

**Comment by pixeltao** [comment]
@birdybro OK sounds good. I'll record those so that we can have a clear comparison. It's gonna take a little while since I'm not setup to capture, but I'll try to upload something by next week. Thanks!

**Comment by birdybro** [comment]
Much appreciated!

**Comment by pixeltao** [comment]
I've managed to capture the audio of Soldier Blade from my TG16 using my old RetroTINK2X hooked to a cheap capture usb dongle. Unfortunately, the capture dongle processes the audio channels to mono.

However, the result isn't completely useless:
SFX 08 and 09 are noticeably louder than SFX 01~06 on my console when compared to your recording of the same SFX on MiSTer.

Here's the file: 
[Soldier Blade sfx 01-09 and 61_TG16Capture.zip](https://github.com/MiSTer-devel/TurboGrafx16_MiSTer/files/6641787/Soldier.Blade.sfx.01-09.and.61_TG16Capture.zip)

My TG16 is a HES-TGX-01
SN: 0235966HB

It's the base model, no idea if it has a specific motherboard revision and since the rf shield is soldered on the board, I'm not too tempted to disassemble it to verify.

**Comment by dshadoff** [comment]
On my own setups, I am not able to hear the difference which you are describing... however, there might be a partial explanation.

If you look at issue #148 , there are recordings of waveforms of waveforms from the sound channel while researching that issue.  The TG16 would have a Hu6280 which would have the spiky waveforms which produce "pops" when any of the volume attributes change for PSG, whereas MiSTer - at the time this issue was logged - would only have those pops when a channel is started/stopped at a high volume.

Try the new release, and see if you notice the difference on this track.  It *won't* be louder.  But the differences between different sound effect tracks may be smaller.  This version will sound more like a SuperGrafx would.

**Comment by pixeltao** [comment]
Thanks for the heads up. The new update doesn't seem to solve the issue unfortunately. And if it reduces the differences, it's very subtle. I redid the comparison between actual TG16 hardware and the MiSTer core (release 20210724), and those PSG channels still sound too quiet on the MiSTer core.

Since no one else seem to notice this, or is able to reproduce this difference, I'm wondering if it's something specific to the revision of my TG16 that'd affect the volume difference between PSG channels on my console. That being said, I do find the audio to sound better the way it's mixed on my console (which leads me to believe I don't have a weird console with unique audio attributes).

I feel like this is a dead end. Should I close this issue?

**Comment by dshadoff** [comment]
Probably should.
I'm not getting anywhere on reproducing it.

**Comment by pixeltao** [comment]
OK I'm closing this issue even though it's not solved.

I find it curious that no one else is hearing this because I don't have this issue with any other core, and I can hear the difference (which can be heard on the recording posted above) via both analog and digital output. It's specific to this core.

One possible lead I can think of: the overall volume of this core is very low compared to all other cores and compared to the  original hardware. I don't know much about coding FPGA, but to me, it looks like the audio signal is reduced too much somewhere. Maybe this creates distortion or increases audio differences with some of the PSG channels.

Also, the "audio boost" feature this core has makes me wonder if it could be part of the issue even though I get that it's needed to have some leeway to balance CD audio vs. PSG audio.

Again, I know I'm talking through my hat, but I'm mentioning these things anyways in case it helps solve this issue and improve the audio of this core.

And thank you for taking the time to look into this.
