### ISSUE TITLE
Attract Mode always stuck at "Press run" screen whenever it loads a PCE SCD game

### ISSUE THREAD

**Issue by Hareluya79** [MiSTer-devel/TurboGrafx16_MiSTer#144]
Hi, 

When you want to run the attract mode script whenever it loads a CD game for TG16 it always on the same "press run" page for 2 mins before switching to another game and still the same "press run" page... so this is more like a request to enable Auto "press run" whenever a game is loaded.

Terraonion's SSDS3 have this feature, wondering if it can be implemented on the cd core.

Much appreciated for your time and consideration.

**Comment by dshadoff** [comment]
This sounds like it should be logged against the "attract mode" script, as it is the expected behavior for CD games to wait for the user to hit <RUN> before anything happens.

**Comment by Hareluya79** [comment]
> This sounds like it should be logged against the "attract mode" script, as it is the expected behavior for CD games to wait for the user to hit before anything happens.

Technically speaking it should be like this, however it will be better if it can be an added feature in the TG16CD core just like SSDS3 (I have it and its really useful)
![Screenshot 2021-06-20 at 11 32 21 AM](https://user-images.githubusercontent.com/58026642/122661339-dbb39100-d1bb-11eb-84b3-6d6f8e34157a.png)
 where you can toggle this option on or off as a core setting , hopefully it can be considered. *pray hard*

**Comment by sorgelig** [comment]
I don't understand why it even in issues? And why it in this repo? 
It's not an issue at all.
