### ISSUE TITLE
Supergrafx demo "Meet the SuperGrafx by Punkfloyd" has excessive pops in PSG sound

### ISSUE THREAD

**Issue by dshadoff** [MiSTer-devel/TurboGrafx16_MiSTer#148]
Most PC Engine related systems used a PSG found in the Hu6280 CPU; all SuperGrafx and some CorGrafx units used a variant of this, in the Hu6280A CPU.

The PSG in the 6280A version of the CPU is known for fewer "pop"/"click" sounds when:
a) enabling a channel (especially at full volume)
b) changing volume suddenly
c) in some cases, just by enabling the channel in order to repopulate the wave buffer

The demo mentioned here seems to be using a) and b) above (I don't believe that MiSTer's core would be affected by c), so the latter portion of the demo has many such "pop" noises, where a real SuperGrafx would not.

The 6280A likely deals with this by damping the sudden volume change with a quick (rather than instantaneous) ramp-up/down of volume - however the speed of this needs to be measured/characterized.

While the SuperGrafx mode in MiSTer should be forced into 6280A mode, this mode should also be available as a choice for regular PC Engine use, as it was available in some devices.

**Comment by sorgelig** [comment]
from other side if only technology demo is affected then it doesn't worth to implement.

**Comment by dshadoff** [comment]
Several games have audible differences between system types; both options should ultimately exist.
Yes, it is a low priority.

Consider this as a "TODO"/feature request for myself, as I will still need to do some primary research to characterize those differences before any changes can be implemented.  (Once understood, I expect the changes to be pretty simple).

**Comment by dshadoff** [comment]
I have written a test program to determine the behaviour on various systems.
button 'I' = toggle channel balance from zero to maximum
button 'II' = toggle global balance from zero to maximum
'DOWN' = toggle channel volume from zero to maximum
'SEL' = toggle channel active flag


[beep.zip](https://github.com/MiSTer-devel/TurboGrafx16_MiSTer/files/6837272/beep.zip)

Results:
- Duo-R system shows an 'offset' when any of these is toggled (offset corresponds with the 'pop') - this is the common Hu6280 PSG
- MiSTer shows an offset only when channel active flag is toggled; others remain 'inline'
- SuperGrafx has no 'pops' / offsets - this is the Hu6280A-type PSG


![](https://cdn.discordapp.com/attachments/723938760600846476/866485815248158730/unknown.png)

![](https://cdn.discordapp.com/attachments/723938760600846476/866484212084637696/unknown.png)

![](https://cdn.discordapp.com/attachments/723938760600846476/866486541378912266/unknown.png)

**Comment by dshadoff** [comment]
Verified this is fixed and available in release 20210724.
