### ISSUE TITLE
Madou Monogatari I - CD Audio Cuts Out

### ISSUE THREAD

**Issue by slahapman** [MiSTer-devel/TurboGrafx16_MiSTer#155]
Hello.

MiSTer v210803
TGFX16 v210725

On Madou Monogatari 1, it seems like if you get into a battle or visit the cat's shop at the very beginning of the game, the CD audio will fail to resume upon the battle ending or leaving the shop.

Tried with both the fan-translation and JP original game (redump verified).

CD seek normal or fast doesn't affect this.

**Comment by dshadoff** [comment]
Log output looks like this:
```
PCECD: Command SAPSP, start = 33117, end = 257301, [1] = 00, [2] = 07, [9] = 40
PCECD: Command SAPEP, end = 49605, [1] = 01, [2] = 11, [9] = 40
PCECD: Command PAUSE, current lba = 34397
PCECD: Command SAPEP, end = 49605, [1] = 01, [2] = 11, [9] = 40
```

The original SAPSP/SAPEP are started when first playing the level.
The PAUSE occurs when an in-game encounter takes place.
After the encounter, SAPEP occurs again - apparently this should change PAUSE state back to PLAY state.

**Comment by dshadoff** [comment]
Watching further, Main_MiSTer actually does resume play, but it seems that the core is still muted (eventually, "PCECD: playback reached the end 33117" message is displayed).  So, this is another case to unmute within the core.

**Comment by dshadoff** [comment]
This issue will be closed after next release.
