### ISSUE TITLE
Question about supported cue sets.

### ISSUE THREAD

**Issue by undeadindustries** [MiSTer-devel/TurboGrafx16_MiSTer#161]
Hi there.
I'm using the japanese 3.0 CD bios. But none of my CD isos that work in retroarch work on Mister.

The problem is probably my iso set?
Each cue has a .img, .ccd and .sub.
No .bin file.

I wasn't sure if that was supported?

Thanks!

**Comment by dshadoff** [comment]
That type of image is not explictly supported, but is possible to work if the files are properly-built and references are good.

However, it used to be a common occurrence that either:
a) time signature indexes are not correct in the original rip, or
b) internal references in the cue file point to an incorrect path, filename, or unsupported MODE type.

You're better off getting fresh rips.
