### ISSUE TITLE
[art of fighting] graphic glitch when zoom-in/out

### ISSUE THREAD

**Issue by xenyou** [MiSTer-devel/TurboGrafx16_MiSTer#178]
"Art of fighting (Ryuuko no Ken)" has graphic glitch when switching zoon-in and zoom-out.
This game uses arcade card.

See this video.
https://www.youtube.com/watch?v=ryn_FA7hTwU

The frames are like this.

![Screen Shot 2022-07-23 at 9 44 20](https://user-images.githubusercontent.com/832358/180583780-bc08f1d2-fbdd-4659-a419-d5cd817f9c64.png)

**Comment by dshadoff** [comment]
I expect that you are seeing these issues on HDMI output, correct ?
If so, this could be in the scaler section, due to resolution changes.

Please confirm whether this is happening on HDMI or CRT.

**Comment by Left-Empty** [comment]
I have tested this and it happens here in HDMI. I tried various settings but nothing takes it away.
I don't have the possibility to test on CRT right now.

**Comment by dshadoff** [comment]
With the help of another user, this has been confirmed to be only present on HDMI, and it's due to the way the scaler currently works when a horizontal resolution changes (which happens frequently in this game).

I will leave this issue open until either the scaler's behaviour in these circumstances can be improved, or some other workaround can be found and implemented.

In the meantime, I have confirmation that it works fine for CRT output.

**Comment by M-Walrus** [comment]
These my findings from testing this morning:
-Analog output via IO board is completely clean.

-Vsync Adjust 0 and 1 both exhibit similar behavior, with 1-3 glitchy frames whenever a zoom occurs.  A partial frame may appear at times, and this frame is from the last time a zoom occurred.
V-sync adjust 1 example: https://youtu.be/jXffuFK_eL4
V-sync adjust 0 example: https://youtu.be/G-Zmszrx2Tg

-Vsync Adjust 2 seems to always work properly when zooming in, but when zooming out has a consistent 2 frames of noise, with no partial frames from the previous zoom as seen in Vsync_adjust 0/1.
V-sync adjust 2 example: https://youtu.be/4LqxYeqamg0

**Comment by xenyou** [comment]
Anyone who tried this cable?

https://ultimatemister.com/product/mister-hdmi-scart-direct-video/

**Comment by dshadoff** [comment]
Since the scaler is the root of the issue, then bypassing the scaler should prevent this from happening.
However, I haven't tried that cable, nor have I tried HDMI direct conversion output on this issue.

**Comment by Toryalai1** [comment]
This is a scaler issue since the resolution changes during zooming. This ticket can be closed

**Comment by xenyou** [comment]
@sorgelig 
Why did you close this?
Are there any other threads discussing this problem?

**Comment by sorgelig** [comment]
This is not related specifically to this core. And it's unlikely will be fixed due to how scaler works.
You may continue to discuss here, but better way to discuss is MiSTer forum.
