### ISSUE TITLE
OSD button hardcoded?

### ISSUE THREAD

**Issue by rogalian** [MiSTer-devel/TurboGrafx16_MiSTer#181]
Possibly something I'm missing.

In the main MiSTer menu I have mapped individual controller buttons for Select, Start and Menu.

In the TG16 core, I have assigned the same buttons.

Pressing the button for "Menu" brings up the OSD, but pressing the button for "Select" also brings up the OSD - which I don't want to happen.

I have to map "Select" to another controller button for it to work independently.

**Comment by dshadoff** [comment]
I think this is related to your specific controller and how you have configured it - this button seems to be behaving in a unique way.  I do not have this problem with an 8BitDo SN30 Pro.
However, I am also aware that some of these controllers have multiple different operating modes, which you might want to clarify as well.

**Comment by rogalian** [comment]
Thanks, it's an M30 2.4G running via the USB receiver. It appears to do the same thing everywhere, I'd only noticed it with the TG16 core as it's the only one I need Select for.

Close this issue. I'll have to ping 8bitdo some messages.
