### ISSUE TITLE
Overscan & Scaling on HDMI

### ISSUE THREAD

**Issue by Nigoli** [MiSTer-devel/TurboGrafx16_MiSTer#182]
I have an issue with HDMI using the core.

I’ve used an actual PC Engine and an upscaler to see every pixel including the overscan ones. When I enable the overscan on the core to hidden. I get some of the pixels cut off toward the bottom. But when I do visible. I see the entire image, but it goes into a tiny picture on 1920x1440 and scale for Narrower HV-Integer.

Setting the scale to Normal fills the image resolution completely. But only when I set it to a integer scale it shrinks it. I normally like to use an integer that’s Narrower depending on what I play and like to see every pixel just like the NES core.

On my CRT it displays fine.

Thanks.

**Comment by sorgelig** [comment]
integer scaling can scale obviously only by integer number. How it will look depends on 1) core resolution 2) HDMI resolution.
Different cores have different resolutions, and therefore may look differently in integer scaling.

**Comment by Nigoli** [comment]
I tried different resolutions. It feels the same way setting it to Normal rather than integer for the scaling, I can't get the narrower way of getting the picture to fill for the core.

There's really no kind of problem for Overscan? I've also been testing the most minimum resolution for PC Engine games.
