### ISSUE TITLE
Is the cheats path of TGFX-16 CD wrong?

### ISSUE THREAD

**Issue by szuping** [MiSTer-devel/TurboGrafx16_MiSTer#205]
I tried other core cheats, they are usually placed in \Cheats\"Console Name"\...
But the cheats(.zip) of TGFX16-CD must be placed in \games\TGFX16-CD\, and the path of cheats(.zip) of TGFX16 (HU-GAMES) is normal...

**Comment by Left-Empty** [comment]
No such issue here. They are in their cheats subdirectory (cheats/TGFX16-CD) and working from there.

**Comment by sorgelig** [comment]
cheats either can be in cheats/TGFX16-CD or in CD's folder.

**Comment by szuping** [comment]
Sorry, this thread can be ended and closed
