### ISSUE TITLE
Soldier Blade (J/U)– Screen Mode Bug

### ISSUE THREAD

**Issue by elrymer** [MiSTer-devel/TurboGrafx16_MiSTer#207]
Enter the "SET UP" mode from the title screen and then toggle the "SCREEN MODE" option from "NORMAL" to "ARCADE". All the text quickly disappears leaving only the solid background color. It is possible to continue by blind-navigating to "EXIT" and the game seems to run normally otherwise.  Same behavior on both digital/analog video output, [corroborated](https://misterfpga.org/viewtopic.php?f=19&t=7971) by one other forum user.

`/media/fat/games/TGFX16# md5sum Soldier*Blade*.pce
45a6dc816ebde2de10e4286d72957770  Soldier Blade (J).pce
59d23b7af39ea827eceb1d7e2cc363c0  Soldier Blade (U).pce`

**Comment by dshadoff** [comment]
I'm on vacation and I'll check this out when I get back to my system in a couple of weeks, but in the meantime, you can document your video output chain, as that might be involved.
So:
- are you using HDMI or analog output (or HDMI direct) ?
- If you are using the HDMI output, what scaler settings, resolution, and screen are you driving ?
- If you are using analog output, is is driving a scaler, an LCD/OLED monitor, or a CRT directly ?

I don't keep a list of MD5 checksums, but I can validate CRC32 from here.

**Comment by elrymer** [comment]
This core looks fantastic over composite to a consumer-grade standard-definition NTSC CRT TV, so that's what I like to use.  Using analog video output with an active adapter.  Same issue over HDMI to a consumer-grade 1080p-native NTSC LCD TV.

Scaler settings and resolution in MiSTer.ini:
`vscale_mode=0`
`vscale_border=0`
`video_mode=8 ; 8 - 1920x1080@60`

Scaler settings and resolution in TGFX16 core OSD:
`Scale:      Wider HV-Integer`
`270x216     15.74KHz  59.8Hz`
`1920x1080  148.07MHz  59.8Hz`

Turns out the (J) dump had some kind of 512-byte header; after I removed it I got CRC32 that matched the bright-green No-Intro Dat-o-Matic entries I learned about today from the other forum user ([J](https://datomatic.no-intro.org/index.php?page=show_record&s=12&n=0331), [U](https://datomatic.no-intro.org/index.php?page=show_record&s=12&n=0332)). No observable change in behavior, though.
`$ crc32 Soldier\ Blade\ \(*.pce`
`8420b12b        Soldier Blade (J).pce`
`4bb68b13        Soldier Blade (U).pce`

I believe my displays can show every-other-field effects just fine in general, either with the MiSTer or with original PCE hardware.

Thank you for commenting here and all your contributions through the decades.  Just wanted to post the bug report after getting corroboration in case it helps any work you'd still like to do.  Hope you are enjoying the vacation!

**Comment by dshadoff** [comment]
OK, I was able to reproduce this on MiSTer, and to find that it doesn't have this fault on real hardware.
It's interesting, and seems to be somehow related to video register settings on a higher dot-clock mode.
I'll take a look at this soon - possibly this week.

**Comment by srg320** [comment]
I made a fix, but tested it only on this game.

**Comment by MP2E** [comment]
Looks like the change works perfectly, I tested across most of the games in the following list in the higher dot clock mode and spotted no issues at all, everything worked as expected.

http://www.tg-16.com/arcade-mode-high-resolution-shmups.htm

**Comment by srg320** [comment]
> Looks like the change works perfectly, I tested most of the games in the following list in the higher dot clock mode and spotted no issues at all, everything worked as expected.

The changes are not related to dot clock. It is related to the VRAM access mode (register MWR: VM=3,CM=0).

**Comment by dshadoff** [comment]
I recommend that the fix gets merged.

Full-scale testing will probably only happen as a result of a merge (that's an unusual combination for MWR setting - nobody knows which games would use that; maybe only this game),

Also, it's a small fix, and easy enough to roll back (or improve) if any new issues appear.

**Comment by dshadoff** [comment]
I just noticed that this was already committed to the core.
Since it fixes the issue, perhaps this issue should be closed.

**Comment by real-amano** [comment]
@elrymer , can you close the report?

**Comment by elrymer** [comment]
Closing report in accordance with a request from real-amano.
