### ISSUE TITLE
[art of fighting] black screen when zooming with analogue I/O

### ISSUE THREAD

**Issue by xenyou** [MiSTer-devel/TurboGrafx16_MiSTer#208]
This issue is similar to a previous one. But this time is using analogue I/O output.

https://github.com/MiSTer-devel/TurboGrafx16_MiSTer/issues/178

Please watch this video. 

https://www.youtube.com/watch?v=hayR3STrN0E

Here is my setup.
- analogue I/O board
- connect with VGA cable
- LCD monitors that support 15khz (Arcooda,  Benq BL912)

The monitors might be the cause. Or swithcing resolutions is too heavy?

**Comment by dshadoff** [comment]
Those blackout pauses are definitely your monitor trying to adjust its internal resolution; this doesn't happen on a CRT (I tested this when issue 178 was filed).

**Comment by xenyou** [comment]
Oh... I see...

Thank you for your information.
