### ISSUE TITLE
A Ressha de Ikou III not booting (CHD image)

### ISSUE THREAD

**Issue by FGKey2040** [MiSTer-devel/TurboGrafx16_MiSTer#217]
Bios loads, hit run, black screen

**Comment by dshadoff** [comment]
OK, the canonical name - if I understand you correctly - is "A.III Ressha de Ikou".

What BIOS are you trying to use ?
It should be the Japanese System 3.0 one.
I'm pretty sure the US BIOS will hang on a black screen, just as you state.

This game also expected that you enable MB128.

**Comment by FGKey2040** [comment]
Yeah, that’s the correct name, sorry!

I’ll have another go tomorrow - I’m pretty sure my arcade BIOS is system 3.0, and I did take a go at MB128. Is it booting for you?

**Comment by dshadoff** [comment]
Yes, it works for me.  It does take 5 to 10 seconds of black screen before the ARTDINK logo appears, but that's normal.

**Comment by FGKey2040** [comment]
Is there anything specific I need to have for the MB128 to function on MiSTer?

**Comment by FGKey2040** [comment]
Hey - sorry, problem solved, looks like the bios update_all pulled was at fault!

**Comment by dshadoff** [comment]
Sounds good.  Please close the issue if it's solved.
