### ISSUE TITLE
Magical Chase crashes stage 3

### ISSUE THREAD

**Issue by Salcade** [MiSTer-devel/TurboGrafx16_MiSTer#26]
I'm on Release 20180925 and cant make it to stage 3...Both US and JPN version. Music messes up and the game just freezes up. Using stock DE10 nano without IO board or ram expansion.  When it crashes can be kind of unpredictable but I  can never make it to stage 3. 

UPDATE: Seems to be a specific issue with 20180925 because I played through the entire game with version 20180919 and it was fine.

**Comment by dshadoff** [comment]
Please verify whether this issue still exists on new release -> Release 20200220

**Comment by Salcade** [comment]
I just played through the entire game with release 20200220, the good news is that It didn't freeze up BUT the store and the try again screen has a weird flickering line/glitch on the bottom of the screen.

**Comment by dshadoff** [comment]
Ok then I suggest closing this issue and opening a new one listing the new issue’s features.
