### ISSUE TITLE
Small graphical glitch in Air Zonk

### ISSUE THREAD

**Issue by cr4zymanz0r** [MiSTer-devel/TurboGrafx16_MiSTer#27]
When you start the game, select a difficulty, and it shows "Stage 1 Toxy Land", it should go to a black screen and stay black until the next selection screen loads. Instead, it goes to a purple-ish screen for a moment instead (the game still continues fine after that).

Tested on release 20180925

**Comment by dshadoff** [comment]
Fixed in commit 20200216 - watch for upcoming release

**Comment by cr4zymanz0r** [comment]
Issue no longer present when testing.
