### ISSUE TITLE
Graphical glitch in intro of Bomberman '94

### ISSUE THREAD

**Issue by cr4zymanz0r** [MiSTer-devel/TurboGrafx16_MiSTer#29]
When you first boot Bomberman '94, the intro starts and after a few seconds there's what looks like a shooting star. There are some graphical glitches on it.

Tested using the 20180925 core

**Comment by cacophony1** [comment]
I see the glitches in the large shooting star as well running with SDRAM. I also noticed that later in the intro when the screen gets a large block of solid white there are added vertical white strips on all four corners that shouldn't be there.

**Comment by dshadoff** [comment]
I made some changes in commit 20200216 which might improve this - watch for next upcoming release, and leave a follow-up comment

**Comment by cr4zymanz0r** [comment]
There still seems to be some glitching in the same scene, but it's not always the same and it doesn't always do it the first time now.

**Comment by dshadoff** [comment]
Please check with new release.  This should be fixed now.

**Comment by sorgelig** [comment]
fixed
