### ISSUE TITLE
Dungeon Explorer title text scroll glitch

### ISSUE THREAD

**Issue by cr4zymanz0r** [MiSTer-devel/TurboGrafx16_MiSTer#31]
On the title screen of the game, after a few moments the text starts to scroll with the story. at the top of the scrolling there will start to be a thin glitchy line that appears to portions of the title logo.
Turns out the glitch is only present on SDRAM, but not on DDR3 RAM

Core version tested: 20181118

**Comment by dshadoff** [comment]
Fixed in commit 20200216 - watch for next upcoming release

**Comment by cr4zymanz0r** [comment]
Issue is no longer present during my testing.
