### ISSUE TITLE
Distorted audio when using Optical Audio out

### ISSUE THREAD

**Issue by pattraynor** [MiSTer-devel/TurboGrafx16_MiSTer#32]
When running optical audio out on the MiSTer using the I/O, the audio is loud and distorted like it was on the MD core. It was fixed there, but the issue still exists on the TG core. The core I was using is 20181118.

Setup:
Nano DE-10
I/O Board using RGBS + Optical audio out with TOSLink mini into AV Receiver.

**Comment by sorgelig** [comment]
it will be fixed

**Comment by sorgelig** [comment]
already fixed
