### ISSUE TITLE
Street Fighter 2: Champion Edition - Graphics glitches 

### ISSUE THREAD

**Issue by M-Walrus** [MiSTer-devel/TurboGrafx16_MiSTer#34]
The bottom couple rows of pixels are constantly glitching during fights.

Also, the screen will randomly flash with different backgrounds/sprites while playing the game, most commonly when using special attacks against enemies.

Tested on 02-18-2019 TGFX16 core - 64 sprite hack OFF - controller set to 6 button, SDRAM used for rom storage, 

only tested via hdmi output 1920x1080 @60hz

tested with both vsync_adjust=0/2 and vscale_mode=0/1 -- occurs in all

issue seems to occur more frequently on certain stages (E.Honda/Japan, Zangief/USSR, etc..)

**Comment by SegaSnatcher** [comment]
I can confirm this happens.

**Comment by c0d3h4x0r** [comment]
I’ve seen this happen too.  Might be a bug in the original game on actual hardware though, as I’ve never owned the original game or played it on the actual hardware.

**Comment by sqwirral** [comment]
Yes, screen flickers every few minutes. Game is fine on real hw..

**Comment by dshadoff** [comment]
I made some changes in commit 20200216 which might improve this - watch for next upcoming release, and leave a follow-up comment

**Comment by sqwirral** [comment]
I tested a build with the latest commit, unfortunately the full-screen flashing is still there for me (not sure if you were referring to that or the bottom row of pixels issue).

**Comment by sorgelig** [comment]
I didn't see full screen flashes. Is there a special scene or any?

**Comment by sqwirral** [comment]
It seems more common on certain stages, such as Zangief. Sometimes you can play for a while without seeing one. M-Walrus said it's worse when doing special moves. I always choose Ken, 6 button mode, and do lots of special moves. Usually get one or two flashes per stage.

**Comment by dshadoff** [comment]
I did see a singular flash on this build, but less than previous builds.
I saw no issues on the bottom row of pixels.
This is why I said "might improve" rather than "fix".

**Comment by M-Walrus** [comment]
Newest update does seem to help a bit, but has introduced some new graphical issues.
I have been testing for the graphics issues on the E-Honda stage because they seemed more common there previously, and with todays update a new graphics glitch is occuring:
https://youtu.be/gVCWTRdlDYE

Watch the top of the stage, above the life bars. As the players move further to the side, that entire top section becomes unstable and on the right side even has some glitchy lines going through the large red lantern hanging from the ceiling.  I did not observe this in the previous builds, including the last 2-12-20 release.

**Comment by dshadoff** [comment]
I was not able to recreate the glitches at the top which you demonstrated; however, I will adjust the BYR latch timing to correct similar-seeming issues on other games.  Hopefully it will also correct the top line glitch here too.  Watch for this within the next few days.

**Comment by sqwirral** [comment]
Just played through SFII' with todays rbf and didn't see a single screen flash. I used to see it every time, has it been fixed?

**Comment by dshadoff** [comment]
Complete rewrite of video core.  I would say that all old bugs need to be re-evaluated and closed if you don't see them anymore.

**Comment by sorgelig** [comment]
I close this issue as VDC/CPU are totally rewritten and old bugs aren't applicable anymore. 
If there are glitches in new release, then open a new issue.
