### ISSUE TITLE
Andre' Panza Kick Boxing - Graphics glitches

### ISSUE THREAD

**Issue by M-Walrus** [MiSTer-devel/TurboGrafx16_MiSTer#35]
Was trying this one out today and found it has glitches in the sprites during animations. The glitches occur all over the screen. If you stay still and the cpu isnt attacking, they go away. 

Turned off all hacks (64 sprite, etc) and extras like 2nd controller, 6 button controller, etc, when testing.

**Comment by sorgelig** [comment]
it's known problem

**Comment by MordecaiWalfish** [comment]
@sorgelig should I be looking somewhere else for known issues? I have been testing tgfx16 extensively and planned on putting all apparent issues here

**Comment by sorgelig** [comment]
Atari Forum has PCE topic where all glitches are noted.
http://www.atari-forum.com/viewtopic.php?f=117&t=32496

**Comment by dshadoff** [comment]
Please check with new release.  This should be fixed now.

**Comment by sorgelig** [comment]
fixed
