### ISSUE TITLE
possible adding tg/pc engine cd support?

### ISSUE THREAD

**Issue by jinx5** [MiSTer-devel/TurboGrafx16_MiSTer#36]
The tg core seams top notch. still needs some fixes but would it be possible adding cd support. From what I hear it's basically running off the main hardware with a bit of extra ram and some other things. Not like the sega cd where it's another system that connects onto the genesis. Would it need it's own core or from what I think can be a additional addon to the existing core. Will they need to replicate the cd drive, making things a bit more difficult or will it not matter much since all it needs to do is read the image?

**Comment by sorgelig** [comment]
There is already some attempt:
http://www.atari-forum.com/viewtopic.php?f=117&t=35171
It's better to discuss it on forum.
