### ISSUE TITLE
Audio and graphics glitches in Pac-Land

### ISSUE THREAD

**Issue by vanfanel** [MiSTer-devel/TurboGrafx16_MiSTer#37]
HI there,

Just to report that this fantastic core still shows small graphical glitches in Pac-Land: upper line of the game area has an overlapping wrong line as scroll advances.
Also, the percussion on the game's music is totally wrong. Compare against original hardware, which sounds like this:
https://www.youtube.com/watch?v=eGs7c5quXqM

**Comment by sorgelig** [comment]
I know about graphical glitches in this game.
Artifacts are small, but it requires total rewrite of VDP. 
Similar glitches are present in some other games.

**Comment by vanfanel** [comment]
The noise channel in PacLand has been fixed, now it sounds right!
Only these graphics glitches remain :)

**Comment by dshadoff** [comment]
Fixed in commit 20200216 - watch for next upcoming release

**Comment by dshadoff** [comment]
Fix is in current release.
Please review and close.

**Comment by sorgelig** [comment]
I close the issue, but actually fix fixes some games but now other games got issues.. 
It still belongs to more deep VDC changes...
