### ISSUE TITLE
Feature request: add turbo buttons/switches

### ISSUE THREAD

**Issue by c0d3h4x0r** [MiSTer-devel/TurboGrafx16_MiSTer#40]
The TurboGrafx-16 stock controllers had built-in turbo switches above the I and II buttons.  Each switch could be set to "slow" or "fast" turbo settings.  Many games (such as Bonk's Adventure) are nearly unplayable without the turbo switches.

Would it be possible to map controller buttons to turbo toggles so we can get the original console's turbo buttons behavior?

**Comment by sorgelig** [comment]
It's called autofire in MiSTer. It's already implemented: 
https://github.com/MiSTer-devel/Main_MiSTer/wiki/Input-devices#auto-fire

**Comment by c0d3h4x0r** [comment]
Okay, that explains why I couldn't find it in the docs.  FYI, in the USA, it was always called "turbo fire", even for other consoles like NES and SNES.
