### ISSUE TITLE
Outrun- Bottom scanline flicker

### ISSUE THREAD

**Issue by black-francis** [MiSTer-devel/TurboGrafx16_MiSTer#46]
Using TurboGrafx16_20190928.rbf with an NTSC region no-intro rom.

In game the bottom scanline randomly flickers, cannot see evidence for this on either software emulation or real hardware videos.

**Comment by dshadoff** [comment]
Fixed in commit 20200216 - watch for next upcoming release

**Comment by M-Walrus** [comment]
I still see some scanline flicker in this game. It's very small and has a variable location at the lower half of the image, usually appearing underneath the horizon line in the game. 
It's easy to see if you pause the game and stare at the still image closely for a short amount of time.

**Comment by M-Walrus** [comment]
Additionally, I also found that the top scanline of the game's view area will flicker when a background element goes that high, like clouds on the first stage when you first start the game:
https://youtu.be/J8ar3yOmjkU

I'm unsure if this is accurate to original hardware, but it seems like it could be related to the issues being tracked in this thread.

**Comment by dshadoff** [comment]
I checked on a real system, and the below-horizon glitches occasionally happen.  However, the single blue line at the top is a clear differentiator.

The BYR latch timing needs to be adjusted by a couple of cycles; I will check in an adjustment soon.

**Comment by sqwirral** [comment]
Is this fixed today? Looks good to me, no flickering, just the blue line like original hw.

**Comment by sorgelig** [comment]
I close this issue as VDC/CPU are totally rewritten and old bugs aren't applicable anymore.
