### ISSUE TITLE
Powerdrift- Graphical glitch

### ISSUE THREAD

**Issue by black-francis** [MiSTer-devel/TurboGrafx16_MiSTer#47]
Using TurboGrafx16_20190928.rbf with an NTSC no-intro rom.

On the character select screen there is a square-ish patch on the left hand side on the screen that flickers like crazy, can also be seen but in a less pronounced manner in game too. Neither software emulation of real hardware footage shows the same problem.

**Comment by James-F2** [comment]
Marked in red here:
![Power Drift (Japan)](https://user-images.githubusercontent.com/31185814/73333569-d70ed580-4272-11ea-97c5-c435340af11f.png)

**Comment by dshadoff** [comment]
Fixed in commit 20200216 - watch for next upcoming release

**Comment by cr4zymanz0r** [comment]
Tested and not seeing this issue as of the latest commits today. I recommend closing the issue.

**Comment by sorgelig** [comment]
fixed
