### ISSUE TITLE
Screenshot (Windows Key + PrtSc) = "SCALER NOT SUPPORTED" error

### ISSUE THREAD

**Issue by thepulserifle** [MiSTer-devel/TurboGrafx16_MiSTer#49]
Attempting to take screenshots using the hotkey "Windows" + PrtSc does not take a screenshot, but instead gives a "SCALER NOT SUPPORTED" error.

Steps to reproduce:
1) Open TG16 core.
2) Load any game.
3) Using a keyboard, press the Windows key in tandem with the PrtSc key.
4) Observe the error.

**Comment by sorgelig** [comment]
It's just because release is too old.
Next release will support it.

**Comment by dshadoff** [comment]
Current release (20200326) contains this functionality.
Please review and close.

**Comment by thepulserifle** [comment]
Working! Closed.
