### ISSUE TITLE
Behaviour with the last version of the core

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/TurboGrafx16_MiSTer#50]
Hi,

Version 200212.

How to reproduce:
* Launch the core TGFX16
* Choose a game
* Launch another core (NES for example)
* Launch again the core TGFX16
=> The previous game start automatically.

I will be the new way or a bug ?

Thanks,

**Comment by dshadoff** [comment]
I see same behaviour in the 20190928 core...

**Comment by wwark** [comment]
thank you I have the same behavior with Neogeo Core.
I have also the same case if I load again the TGFX16 core the last game is played automaticaly.
It is maybe another change in Mister not related to the TGFX16 core.
I let this issue opened for @sorgelig  to see it.
Previously normally the game is not played automaticaly.

**Comment by sorgelig** [comment]
it's normal because game is in SDRAM which is not cleared between cores. SDRAM is cleared when you start Menu core. So if previous core doesn't use SDRAM or nothing loaded, then going back to TGFX will start the game

**Comment by wwark** [comment]
ok thank you for the explanation. I close this ticket.
