### ISSUE TITLE
Magical Chase crashes on stage 2 on release 20200212.

### ISSUE THREAD

**Issue by bootsector** [MiSTer-devel/TurboGrafx16_MiSTer#51]
Magical Chase crashes in the stage 2 opening screen on release 20200212.

Stage 2 used to play fine on previous version.

**Comment by dshadoff** [comment]
Looking at issues #25 and #26, I’m not convinced that this is unrelated, given the apparently random nature of the report.

Which version (US or JP) was the subject of this report ?

**Comment by bootsector** [comment]
US version.

#25 and #26 don't seem to happen for me on previous version when selecting SDRAM instead of DDR.

**Comment by dshadoff** [comment]
Was this issue found while using SDRAM, or DDR3 ?

**Comment by bootsector** [comment]
SDRAM. 128MB.

**Comment by bootsector** [comment]
Latest changes seem to have fixed this. I will test a little more and report back!

**Comment by bootsector** [comment]
Yes, commit https://github.com/MiSTer-devel/TurboGrafx16_MiSTer/commit/e8f3c6206ecb85f51bca6ec2c7e52b0dabd95bc6 definitely fixed this!

**Comment by bootsector** [comment]
Reopening as this is happening again with latest version. https://github.com/MiSTer-devel/TurboGrafx16_MiSTer/issues/25 is also happening.

**Comment by matthargett** [comment]
my setup: they are alliance AS4C32M16SB-7TIN (it's the 128mb model). it's SDRAM

**Comment by bootsector** [comment]
I can't reproduce the issue on TurboGrafx16_20201114. Issue happens on TurboGrafx16_20201116 and TurboGrafx16_20201117.

**Comment by dshadoff** [comment]
I worked with them and verify that they are seeing this on a valid ROM.  I can't reproduce on my own system, but I believe that this is real.

One more note - They are reporting that this has a higher likelihood if the game waits at the title screen for a bit.  Also, they are using OSD "Reset" to restart the game (although it has also happened on boot from a power off state).

**Comment by bootsector** [comment]
Pasting my procedure from Discord, as it is reproducible in my case and it happens right before stage 1 starts: 

`Turned MiSTer on. Started JPN Magical Chase. Left intro run for a couple seconds (this seems to be important). Pressed start. Selected the middle  difficulty option. Left the transition to the first stage run. Stage started fine. Hit the OSD button -> selected reset. Repeated everything, it's now hanged in that screen`

**Comment by bootsector** [comment]
Any chances we're dealing with memory refresh issues like we had with the SNES core in the past that affected some Squaresoft RPGs? I remember @srg320 having a RAM module that allowed him to replicate the issue and fix the SNES core back then. Hopefully his RAM module will allow him to reproduce and fix this as well? 🤔

**Comment by bootsector** [comment]
Last commit has this issue fixed based on my tests! <3
