### ISSUE TITLE
[Request] Optional Turbo Buttons

### ISSUE THREAD

**Issue by edru** [MiSTer-devel/TurboGrafx16_MiSTer#54]
I would like to request a way to assign the 2 other turbo states to buttons, or assign buttons to toggle through the various turbo states.

I know this was originally on the controller itself, but it isnt often to come across a controller with the correct turbo values.

**Comment by sorgelig** [comment]
You have 2 sets of buttons to assign. Assign 2 different buttons for Fire. Then enable autofire for one button only. So you will have normal and autofire buttons at the same time.

**Comment by dshadoff** [comment]
Also, Core Grafx & TurboGrafx Mini line of consoles has compatible controllers with turbo functionality (except only the pack-in controller with PC Engine Mini).

**Comment by sorgelig** [comment]
It's not an issue actually.
Functionality is present.
