### ISSUE TITLE
Gomola Speed - Certain enemy sprites are glitchy

### ISSUE THREAD

**Issue by M-Walrus** [MiSTer-devel/TurboGrafx16_MiSTer#55]
Watch the demo loop and on the second demo you will see enemies that have both vertical and horizontal glitchy lines through them.

Happens in all previous releases and current public build (2020-02-20)

**Comment by srg320** [comment]
It also happens on a real PC Engine.

**Comment by M-Walrus** [comment]
Closing per srg320's confirmation of this occurring on real hardware.
