### ISSUE TITLE
Magical Chase issue flicker/glitch  (Release 20200220)

### ISSUE THREAD

**Issue by Salcade** [MiSTer-devel/TurboGrafx16_MiSTer#57]
When playing US version Magical chase and entering the shop and also the "try again" screen it has a weird flickering line/glitch on the bottom of the screen. Previous releases did not do this. Thanks!

**Comment by dshadoff** [comment]
Adjusting BYR latch timing corrects this (currently 6 cycles before render pipeline; 8-9 is better).
I will check in an adjustment soon.

**Comment by dshadoff** [comment]
Please check with new release.  This should be fixed now.

**Comment by sorgelig** [comment]
fixed
