### ISSUE TITLE
Dragon's Curse, jittery enemies when screen scrolls

### ISSUE THREAD

**Issue by cr4zymanz0r** [MiSTer-devel/TurboGrafx16_MiSTer#59]
Just start the game and the first snake enemy you come across looks all jittery when you make the screen scroll. This does not happen on the real console.

Tested with both the latest release and the latest commits from today and both had the issue.

**Comment by evidencedj** [comment]
This happens for me as well. I have uploaded a video with this issue. I have got Adventure Island for my PCEngine as Hucard and this does not happen there.

[https://www.youtube.com/watch?v=mrG53t43ni0](url)

**Comment by dshadoff** [comment]
Please check with new release.

**Comment by sorgelig** [comment]
fixed.
