### ISSUE TITLE
Core Parity Request: Have Menu appear at startup if no bootrom selected

### ISSUE THREAD

**Issue by thepulserifle** [MiSTer-devel/TurboGrafx16_MiSTer#60]
In keeping with the other console cores, the menu should appear at startup if no bootrom is found. Currently, if no bootrom is found, the core sits at a black screen until the menu button is toggled/pressed.

**Comment by dshadoff** [comment]
I think I can easily add this if you point out an example core which includes it (as example code).

**Comment by thepulserifle** [comment]
Both NES and SNES cores do this

**Comment by dshadoff** [comment]
I have submitted a pull request with this functionality.
Hopefully it will included soon and a release created soon afterward.

**Comment by dshadoff** [comment]
This functionality is in the 20200326 release; please verify and close this issue.

**Comment by thepulserifle** [comment]
Working well. Closing issue!
