### ISSUE TITLE
R-Type USA Shimmering

### ISSUE THREAD

**Issue by GreatHierophant** [MiSTer-devel/TurboGrafx16_MiSTer#61]
When playing the USA version of R-Type, the line where the status bar meets the edge of the screen flickers constantly.  Similarly, the first line displayed also shimmers when displaying anything other than black.  This does not occur in the Japanese R-Type I and R-Type II ROMs.

**Comment by raygan** [comment]
I'm seeing this as well, over both RTG and HDMI:
![ezgif com-optimize](https://user-images.githubusercontent.com/2982111/78944174-ea180000-7a82-11ea-8d7f-5b7488c8b7de.gif)
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/2982111/78944183-f13f0e00-7a82-11ea-8d50-448d8703f456.gif)

**Comment by dshadoff** [comment]
Please check with new release.  This should be fixed now.

**Comment by sqwirral** [comment]
Looks fixed to me.

**Comment by sorgelig** [comment]
fixed
