### ISSUE TITLE
Kato-Chan, Ken-Chan: graphical glitches

### ISSUE THREAD

**Issue by mathieulh** [MiSTer-devel/TurboGrafx16_MiSTer#66]
Graphical glitches are present in the intro.

https://imgur.com/a/we3Afj1
![WhGiHjY - Imgur](https://user-images.githubusercontent.com/203427/77164685-1ad2ce00-6ab1-11ea-8a1a-e0f751cc51de.jpg)
![ebtEFU4 - Imgur](https://user-images.githubusercontent.com/203427/77164690-1d352800-6ab1-11ea-810a-556387a471d8.jpg)

**Comment by romevi** [comment]
I was JUST about to post this! I meant to post about this last week. The same is the case for the westernized JJ & Jeff. It didn't do this before I updated the core.
It's not just during the intro, either; it's whenever there's a cutscene, like in the rooms when you get health, etc.

**Comment by dshadoff** [comment]
Please state date of release of the core.

**Comment by mathieulh** [comment]
I used the latest build, I also used Sorg's latest commit but that did not fix it
https://github.com/srg320/TurboGrafx16_MiSTer/pull/3

**Comment by romevi** [comment]
> I used the latest build, I also used Sorg's latest commit but that did not fix it
> [srg320#3](https://github.com/srg320/TurboGrafx16_MiSTer/pull/3)

I'm using the latest release 20200326 and it still isn't fixed.
