### ISSUE TITLE
boxyboy game character not show while playing

### ISSUE THREAD

**Issue by psziel** [MiSTer-devel/TurboGrafx16_MiSTer#67]
Starts fine but when you start to play you cant see the guy to move the pieces so you are playing blind

**Comment by dshadoff** [comment]
Please state date of release of the core.

**Comment by psziel** [comment]
V200220. Sorry thought I put that In there Sent from Mail for Windows 10 From: David ShadoffSent: Saturday, March 21, 2020 3:34 PMTo: MiSTer-devel/TurboGrafx16_MiSTerCc: psziel; AuthorSubject: Re: [MiSTer-devel/TurboGrafx16_MiSTer] boxyboy game character not show while playing (#67) Please state date of release of the core.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by dshadoff** [comment]
Please check with new release.  This should be fixed now.

**Comment by sorgelig** [comment]
fixed.
