### ISSUE TITLE
SuperGrafx: Madou King Granzort - graphical glitches

### ISSUE THREAD

**Issue by k-u-r-u-p-t** [MiSTer-devel/TurboGrafx16_MiSTer#68]
SuperGrafx: Madou King Granzort (Japan) 

game character not show while playing on cores 20200220, 20200326

works on core 20200212

**Comment by Aquas77** [comment]
Seconded.

**Comment by brendan1495** [comment]
Same here, thought it was just me

**Comment by sorgelig** [comment]
This is not forum or chat! Please stop "me too" spam.

**Comment by dshadoff** [comment]
Please check with new release.  This should be fixed now.

**Comment by sorgelig** [comment]
fixed
