### ISSUE TITLE
Ys Book 1 & 2 audio glitching

### ISSUE THREAD

**Issue by mario-64** [MiSTer-devel/TurboGrafx16_MiSTer#72]
First of all GREAT JOB on the TG16-CD core! 

I've been playing some games this morning and have noticed that Ys Book 1&2 has a reproducible audio glitch in the opening where the dark clouds and lightning are on screen. Reboot or reset doesn't fix it and it seems to just be one spot. The rest of the intro plays correctly. Is this a known issue?

**Comment by sorgelig** [comment]
In the very beginning with blue clouds?
I don't hear any problem.

**Note:** there are many bad PCE CD rips are floating around.

**Comment by mario-64** [comment]
Yes. I’ll rip my copy again today but the same image works fine on SSDS3

**Comment by Kitrinx** [comment]
Please also verify that the CD files are unzipped, zipped files will not run correctly.

**Comment by mario-64** [comment]
Yep. Same with SSDS3. Using raw bin / cue files. I’ll rip again today and see if it persists

**Comment by sorgelig** [comment]
Make sure "CD Seek" option is set to "Normal".

**Comment by mario-64** [comment]
Thanks. It is. Didn’t change any of the default settings. Using Japan Super System 3.0 card also

**Comment by mario-64** [comment]
I've worked on this all day long with no success. I have re-ripped my personal copy and downloaded other redump validated copies. I even rebuilt a brand new SD card from scratch, updated it and put the games on it. Same issue. Attached is a video file showing it. Audio glitch is at the 16 second mark

[IMG_2194.zip](https://github.com/MiSTer-devel/TurboGrafx16_MiSTer/files/4641150/IMG_2194.zip)

**Comment by dshadoff** [comment]
What brand of SDCard are you using ?  I don't see this issue on my Sandisk, but I have heard of various hiccups and delays on other brands (including Samsung).

**Comment by mario-64** [comment]
The new one I built today was 128 SanDisk. Original was a 512 Gigastone

**Comment by mario-64** [comment]
I also tested using a SanDisk USB jump drive. Same issue

**Comment by cr4zymanz0r** [comment]
I just tested with a self-rip of my original disc and there was a quick hiccup in the CD audio right as the dark clouds appear in the intro right after the copyright screen.

**Comment by Kitrinx** [comment]
This appears to be related to the hdmi mode switching at just that moment while vsync_adjust=2 is active. Can you try vsync_adjust=0 and confirm that changes the behavior?

**Comment by mario-64** [comment]
> I just tested with a self-rip of my original disc and there was a quick hiccup in the CD audio right as the dark clouds appear in the intro right after the copyright screen.
> 
> * running it from SMB share using a wired connection.
> * seems to happen at the same spot every time when I let the intro loop
Yes exactly!!! So glad it's not me. For what it's worth, I managed to get it to play one time without glitching by setting CD Seek to Fast, but then when the intro played for the second time it glitched again. I think this is indeed some sort of core issue. I've tested many, many rips today, different storage types and even build a brand new SanDisk SD card.

**Comment by mario-64** [comment]
> This appears to be related to the hdmi mode switching at just that moment while vsync_adjust=2 is active. Can you try vsync_adjust=0 and confirm that changes the behavior?
I normally use vsync 1 but also tested using no MISTer.ini and got the same issue. No ini = vsync 0 correct?

**Comment by cr4zymanz0r** [comment]
The glitch happens for me on analog audio using a CRT. vsync_adjust wouldn't affect that would it?

**Comment by Kitrinx** [comment]
It does for me. Analog audio has it when vsync_adjust=2, and does not with 0. Tested back and forth several times. Maybe it's related in an obtuse way.

**Comment by cr4zymanz0r** [comment]
I set vsync_adjust=0 and that kept the sound hiccup from happening. Weird.

**Comment by mario-64** [comment]
Ok let me test that as well. I assumed removing MISTer.ini would default it to 0. I’d prefer not to have to use 0 though so hopefully the root problem can be fixed

**Comment by sorgelig** [comment]
i found the source of issue.
will be fixed.

**Comment by mario-64** [comment]
> i found the source of issue.
> will be fixed.

Excellent thank you sorgelig!

**Comment by mario-64** [comment]
New update fixes this issue. Thanks again :)
