### ISSUE TITLE
Button mapping feature request

### ISSUE THREAD

**Issue by blackjer** [MiSTer-devel/TurboGrafx16_MiSTer#73]
Now that PCE CD support has been added with 6 button support can the order for the button mapping be changed?  Currently, after mapping buttons I and II it asks for select and run and then asks for buttons III, IV, V, and VI.  Having it ask for all buttons in order before or after select and run would be appreciated.

**Comment by sorgelig** [comment]
6 buttons support is present from very early release. 
It asks in sequence: main controller buttons and then extra buttons. 99% of games don't need them, so you can skip all of them by pressing enter after run button.
