### ISSUE TITLE
Sometimes needs full reset

### ISSUE THREAD

**Issue by dshadoff** [MiSTer-devel/TurboGrafx16_MiSTer#75]
CDs sometimes require a full reset (RESET button) between games in order to function properly.

EDIT: I mean it requires the hardware RESET button to be pressed.

**Comment by sorgelig** [comment]
by RESET button you mean "USER" button or MiSTer HW RESET button?

**Comment by Left-Empty** [comment]
I have experienced a corruption of sort twice (once with 1552 Tenka Tairan, another time with Tokimeki Memorial), which required a reload of the core to proceed.
I have experienced a few "stuck on load" games, but I think each time I was switching between Fast and Normal CD access — Switching that option seems to require a user reset.

**Comment by dshadoff** [comment]
Different issues exist with each type of reset:

Run+Select:  If this is done while playing audio, pressing Run at the CD screen won't load data from the virtual disk, and the game cannot restart.

Changing games: This is probably due to residual data in memory/VRAM/etc. or hardware settings... but strange behaviour occurs occasionally, which requires RESET button.  These are less frequent than the RUN+SELECT above, but still happen.

**Comment by tlaloc-q** [comment]
RYŪKO NO KEN / ART OF FIGHTING (ACD) has a mini-game called "Daikon (Carrot?) Cut" that is accessible on actual hardware, right? But it seems it is not capable of being accessed with consecutive Select+Run / in-core 'Soft-Resets'.
The hardware reset button won't correct this issue, but perhaps this can serve as a good test to see if later cores fix this.

**Comment by sorgelig** [comment]
with new release reset should be cosistent.
As for RYŪKO NO KEN - it's unclear how to call that mini game even in real HW. So it appears totally unrelated issue (if any).

**Comment by Left-Empty** [comment]
Inded: while magazines said you had to reset three times to summon it, I remember having to do quite many tries on the real console for the thing to show up. Never quite figured it.
I have yet to be able to summon it in the core, but I'm not patient enough anymore: I gave up after 5 tries!

**Comment by sorgelig** [comment]
Do i need to wait for final screen before pressing run+select or i have to press as early as possible? What is the strategy?

**Comment by Left-Empty** [comment]
You have to wait for the warning panel and the terrible laugh to end, supposedly. The game is supposed to begin after waiting for an unspecified time after the warning screen. 
There are various listing: a Japanese magazine listed you needed to reset 3 times, another one said it had to be done only once.

**Comment by tlaloc-q** [comment]
I thought it was a related issue, but i found that if i only soft-reset twice w/ SELECT+RUN and wait for five (5) seconds after hearing the annoying laugh a third time, the mini-game comes up.

**Comment by sorgelig** [comment]
oh, really! it works!

**Comment by dshadoff** [comment]
I was able to get to the mini-game too.
While my testing on this has been limited, I'm convinced enough to close it now, and will reopen or resubmit if I find an example of misbehaviour.
