### ISSUE TITLE
Graphical issues in Popful Mail, Burai, and Valis 1

### ISSUE THREAD

**Issue by Peredonov** [MiSTer-devel/TurboGrafx16_MiSTer#76]
**1. Magical Fantasy Adventure - Popful Mail**: A couple of very apparent graphical glitches during the first intro sequence (before title screen), especially some garbage graphics on the side for some moment, and the heroine's face glitches out before she winks near the end of the intro sequence.
-Note: This is an Arcade Card enhancement compatible game, glitches appear with Arcade card enabled and disabled. 

**2. Burai** (the first one, not Burai II): Start the game and enter the first town toward the north, the field portion of the screen and the status bar in the bottom of the screen both twitch randomly. ----Note: This glitch also occurs in the Madnafen emulator.

**3. Mugen Senshi Valis**: Minor glitch on Reiko's (red short hair girl) briefly in second half of intro sequence.
-Side note: this sequence shows what a great job has been done with seek time, lip sync is perfect, which has not been the case even on some real hardware.

And thank you for all the work that led to this core. It is already better than SSDS3 and even most real drives that need a lot of maintenance.

**Comment by sorgelig** [comment]
first issue is known.

**Comment by Left-Empty** [comment]
About the Valis issue, you forgot a word Peredonov, it is Reiko's Umbrella that exhibits the glitch.

Another testament to the MiSTer's incredible video quality is that I have owned the game for over 25 years, played it on many consoles plugged in RGB or composite, and it is the first time I notice many of the little extra animations and details that were probably lost in the blurriness of poor cabling before, like Reiko's eye twitching, or the blow getting out of the Valis sword to the demon's forehead.

**Comment by dshadoff** [comment]
These should all be fixed in the 20200526 release; please verify and close.

**Comment by Peredonov** [comment]
Just did a quick check on each of these, can confirm they are all fixed. Fantastic work! Closing now.
