### ISSUE TITLE
Star Parodier (NTSC-J) no CD audio after beating first boss

### ISSUE THREAD

**Issue by jfroco** [MiSTer-devel/TurboGrafx16_MiSTer#77]
After beating first boss, there is no more CD audio .
Tested with two different CD images, same problem at the same moment

- [REDUMP] Disc Image Collection: NEC - PC Engine CD & TurboGrafx CD updated 2020-April-30 - Star Parodier (Japan).zip  (cue + bin files)
- Emuparadise - Start Parodia (NTSC-J) (cue + iso file)

Thank you very much for giving us this incredible core!

**Comment by bootsector** [comment]
Stage 2 has audio here for me. Did you update Main MiSTer as well?

**Comment by cr4zymanz0r** [comment]
Stage 2 has audio for me as well. Playing from a self-ripped original disc.

**Comment by jfroco** [comment]
> Stage 2 has audio here for me. Did you update Main MiSTer as well?

That made the trick. Sorry, I didn't read the Patreon message before testing: "Note: You must update Main to latest version!"

Thanks!
