### ISSUE TITLE
Valis 2  Audio track repeats during the intro.

### ISSUE THREAD

**Issue by SegaSnatcher** [MiSTer-devel/TurboGrafx16_MiSTer#81]
It appears a track gets repeated during the intro.   Another user tried different dumps of Valis 2 and they all had the same issue, so not a bad dump of the game.

**Comment by Left-Empty** [comment]
I can confirm it happening not only in the intro, but all the cutscenes: every other scene got the previous track repeated. I seem to remember the CD layout being quite special (data track in between cd tracks all over the cd?).

I tested also the Valis Visual Collection, and in that "game", the audio doesn't repeat, but goes silent every other track. The game features Valis 2, 3 and 4 cutscenes, and the glitch happens only during Valis 2 scenes' playback.

**Comment by KawaiiDinosaur** [comment]
Was going to report this same issue.

**Comment by SegaSnatcher** [comment]
I tested a new MiSTer Main build with latest commits and it seems to have fixed this issue with Valis 2.  I'll wait until it gets officially released before I close this issue.

**Comment by KawaiiDinosaur** [comment]
Fixed for me in latest Main and core builds.
