### ISSUE TITLE
Sound effect variance in  rondo SCD

### ISSUE THREAD

**Issue by Sarvets** [MiSTer-devel/TurboGrafx16_MiSTer#84]
checked with 2 different roms (original dump in archicve and the (FABT/FACT) dump in redumps  in dracula SCD and the basic skeleton death death is stage 1 sound is really low. also holy water break sound effect is low. apparently this crossed over into the translation one as well.  otherwise its amazing. thanks for the hard work!

**Comment by Kitrinx** [comment]
Emulators, ODE, and even different PCE systems have different balances between CD audio and PSG. In the latest release, the audio has been turned around a white PC Engine with super CDROM addon. The levels have been verified with MDFourier.
![DA__ALL_A-PCEW_72406235_F8XD-ndp_vs_mister20](https://user-images.githubusercontent.com/15653832/82332942-1002bf80-99b4-11ea-98fc-e2aa1abbdc1f.png)

**Comment by Chocobobobo** [comment]
The audio boost in today's release made a huge difference. (I am using X4, and no need to adjust the monitor sound just for this core anymore)

Would it be possible to take it one step further and add the option to adjust separately the volume for PSG and CD audio? With that, it should make everyone happy and give the end user enough parameters to "recreate" all the different PCE hardware revisions.
Thanks and keep up the great work!

**Comment by Sarvets** [comment]
thanks so much for all the hard work! Sorry i forgot to close this oops. Big salute
