### ISSUE TITLE
Valis lll - Missing block of pixels during intro.  

### ISSUE THREAD

**Issue by SegaSnatcher** [MiSTer-devel/TurboGrafx16_MiSTer#88]
(Update: The recent commit for Valis 1 also fixed this issue. Will close after new official release.)  

During the intro after the evil Emperor kills the people who "Object", you can see a block of missing pixels in his sword and can see through to his sprite layer.  

![IMG_8332](https://user-images.githubusercontent.com/36483667/82370006-73551780-99dd-11ea-8ade-2dce5bf555d4.JPG)

**Comment by dshadoff** [comment]
Please retest with 20200526; should be fixed.

**Comment by SegaSnatcher** [comment]
Confirmed fixed.
