### ISSUE TITLE
Resolution Issues

### ISSUE THREAD

**Issue by mjj03301977** [MiSTer-devel/TurboGrafx16_MiSTer#89]
240p test suite still has resolution issues in the grid tests. Each resolution has two tests in the suite. Most all resolutions are now cut off at the bottom or the image is off-center? Some of them appear to be slightly moved to the right.

Here are a few examples:
![IMG_0597](https://user-images.githubusercontent.com/65627761/82378270-b44b2d00-99d9-11ea-9bbe-625d088d47d3.jpeg)
![IMG_0595](https://user-images.githubusercontent.com/65627761/82378164-8c5bc980-99d9-11ea-8a3f-97d257bf18b6.jpeg)
![IMG_0598](https://user-images.githubusercontent.com/65627761/82378202-9bdb1280-99d9-11ea-884f-d7d9a4e8e0f6.jpeg)

**Comment by sorgelig** [comment]
already discussed here: https://github.com/MiSTer-devel/TurboGrafx16_MiSTer/issues/80
