### ISSUE TITLE
Allow CD BIOS to be detected in bootroms folder

### ISSUE THREAD

**Issue by jose-cardoso** [MiSTer-devel/TurboGrafx16_MiSTer#91]
The CD BIOS file can currently be located in any of the following locations for the core to function correctly:

```
TGFX16-CD/cd_bios.rom
games/TGFX16-CD/cd_bios.rom
games/TGFX16-CD/<game>/cd_bios.rom
```

Allow the following location to also be used as per https://github.com/MiSTer-devel/Main_MiSTer/wiki/Folders-and-File-naming:

```
bootrom/TGFX16-CD.rom
```

**Comment by Peredonov** [comment]
Rename the CD bios as TGFX16.rom (without "-CD") and put it in the bootrom folder. The core for CD is the same as for regular TGFX16.
I've actually been using the CD bios as the bootrom for this core way before the CD support was added, to make it feel like a real PCE with a system card inserted.

**Comment by jose-cardoso** [comment]
Didn't occur to me to try that. I've given that a go and, while it does seem to work, the core still flashes up the error `CD BIOS not found!` and then continues booting into the selected CD game.

It's clearly still expecting this file to exist in one of the first 3 paths above so the logic may just need tweaking to also check the `bootrom` folder for either `TGFX16.rom` or `TGFX16-CD.rom` to prevent the error message displaying.

**Comment by Peredonov** [comment]
You still need another copy of the bios in the Games/TGFX16-CD folder that has the folders for your CD games, and this copy has to be renamed cd_bios.rom (making sure you're changing the file extension and not just the name).
With two copies of the bios in the above mentioned directories, there is no "CD BIOS not found!" error. Confirm this yourself and then close this issue.

**Comment by jose-cardoso** [comment]
I'm aware that having `cd_bios.rom` in the `Games/TGFX16-CD ` gets rid of the error but that is not a solution.

If `bootrom/TGFX16-CD.rom` already exists the core should simply accept that and not expect a duplicate to exist somewhere else. This goes against the behaviour of other cores.

**Comment by sorgelig** [comment]
cd_bios.rom is not boot rom.

**Comment by jose-cardoso** [comment]
And yet the core boots with that ROM in the bootroom folder. Kinda contradictory to your wiki documentation regarding folder/file paths if you ask me and seems like a half-arsed approach to handling the CD BIOS. But hey, close away and ignore user feedback.

**Comment by Left-Empty** [comment]
Those are just dump of system cartridges. They behave exactly like you'd expect them to if you put them as boot.rom : they boot the console, but you didn't put a cd yet, so they can't boot it.
The CDs require them also as an accessory to their boot.
This all works exactly like the real console would.

**Comment by sorgelig** [comment]
bootrom folder serviced mostly arcade cores to avoid many roms in the root or many folders for each arcade. Now arcades are changed and bootrom folder is basically obsolete. Will be removed in the future. Main boot rom folder is home folder of the core.

**Comment by jose-cardoso** [comment]
I'm aware of how the console and the CD expansion work given that I own both.

The point I'm making is from a user's perspective if I have `bootrom/TGFX16.rom` present on my MiSTer device and I launch the core I naturally see the CD boot screen sitting there waiting patiently until I insert something. I then go to the core's menu, select a CD and hit `Run`. I see no need for the core to complain about a missing CD BIOS file.

If the file simply wasn't present in any of the folders then fine but when that file is present in the `bootrom` folder, the core starts and the CD launches perfectly fine. Ergo that error message is redundant.

But hey just my two cents. Ignore as you please.

**Comment by jose-cardoso** [comment]
> Main boot rom folder is home folder of the core.

Is this true though? If I want to have the following folder structure on my MiSTer this doesn't currently work:

```
TGFX16-CD/cd_bios.rom
games/TGFX16-CD/<game 1>
games/TGFX16-CD/<game 2>
games/TGFX16-CD/<game 3>
```

Either the BIOS and games all live in the root folder or they all live in the games/ subfolder. I can't split them as above for organisational purposes as the core sees the BIOS in the first folder then ignores the games folder when selecting a game.

**Comment by sorgelig** [comment]
bootrom folder serviced mostly arcade cores to avoid many roms in the root or many folders for each arcade. Now arcades are changed and bootrom folder is basically obsolete. Will be removed in the future. Main boot rom folder is home folder of the core.
Some cores such as NES need several boot cores like boot0.rom, boot1.rom... This case is not handled in bootrom folder.  As said above bootrom folder was a half-arsed solution for arcades before mra.

**Comment by sorgelig** [comment]
don't duplicate the folders on different places!
Either you choose games folder for everything, or subfolder in the root. Doing both will mess the things and something will stop working.

```
games/TGFX16-CD/cd_bios.rom
games/TGFX16-CD/<game 1>
games/TGFX16-CD/<game 2>
games/TGFX16-CD/<game 3>/cd_bios.rom (if some game needs specific bios)
```

**Comment by Peredonov** [comment]
> And yet the core boots with that ROM in the `bootroom` folder.
> 
> Your closing response contradicts your wiki documentation regarding folder/file paths and just highlights what appears to a half-arsed approach to handling the CD BIOS.
> 
> But hey, close away and ignore user feedback.

As explained more than once already, the core can do exactly what you requested already, you were getting an error because of your own mistake in placing files in incorrect directories. If set up correctly, you will not see the error you complained about. There's nothing half-arsed in the CD Bios handling, but only in your ability to figure things out on your own. 

Be more appreciative both of the work done for this core and of the guidance you got promptly here to resolve your problem.

**Comment by jose-cardoso** [comment]
> Either you choose games folder for everything, or subfolder in the root. Doing both will mess the things and something will stop working.

So I've noticed. I'll stick to leaving it in the recommended location.

**Comment by jose-cardoso** [comment]
> As explained more than once already, the core can do exactly what you requested already, you were getting an error because of your own mistake in placing files in incorrect directories. If set up correctly, you will not see the error you complained about. There's nothing half-arsed in the CD Bios handling, but only in your ability to figure things out on your own.

No you failed to comprehend the point I was making. Kindly move along.

> Be more appreciative both of the work done for this core and of the guidance you got promptly here to resolve your problem.

I am appreciative @sorgelig's work in more ways than one. Your contribution to this issue, less so since again you failed to get my point. So again kindly move along.

**Comment by Peredonov** [comment]
> I am appreciative of @sorgelig's work in more ways than one. Your contribution to this issue, less so, since again you failed to get my point. So again kindly move along.

We got your point, but you seem to not understand that you always need to select a CUE file for the CD game after you get to the bios screen, which will simply show the bios screen again, just like it would be on real hardware until you press the Run button (as Left-Empty also mentioned). It would not make sense to expect a different behavior. But yes, everyone will move along now as this is not an issue.
