### ISSUE TITLE
Laplace no Ma: Graphical glitches in dungeons

### ISSUE THREAD

**Issue by Left-Empty** [MiSTer-devel/TurboGrafx16_MiSTer#95]
Laplace no Ma displays heavy graphical glitches as soon as the first step is taken in the dungeon view (you can check it by exiting the inn on start and going straight to the top most building after loading the attached dummy save).

[save.zip](https://github.com/MiSTer-devel/TurboGrafx16_MiSTer/files/4668931/save.zip)

**Comment by srg320** [comment]
Can you show a screenshot of this glitch?

**Comment by Left-Empty** [comment]
It was tough capturing it with my old phone!

Here is what happens during a split second when moving:
![IMG_2230](https://user-images.githubusercontent.com/62087454/82686635-7149bd80-9c56-11ea-9a50-5a119ba89899.JPG)


And here is the result after the move: there are glitches on the left, as well as band of glitch on the right in the view area.
![IMG_2228](https://user-images.githubusercontent.com/62087454/82686615-6858ec00-9c56-11ea-83c6-2483ecc7f349.JPG)

**Comment by Chocobobobo** [comment]
Pro tip to grab screenshots, connect a USB keyboard, and press windows key + print screen.
The screenshot will be in the screenshots folder.

**Comment by dshadoff** [comment]
Please retest with the 20200526 release

**Comment by Left-Empty** [comment]
Totally fixed, thank you!
