### ISSUE TITLE
Genso Tairiku Auleria: black screen instead of opening intro sequences.

### ISSUE THREAD

**Issue by Left-Empty** [MiSTer-devel/TurboGrafx16_MiSTer#96]
After inputing your name, the screen goes black and nothing of the cutscenes is being displayed for the next ten minutes, excepting, strangely, for a very small shot in the middle of one of the sequences (I tagged it at the right time on here https://www.youtube.com/watch?v=AxPeGrEpLKs&feature=youtu.be&t=355 — you see the five villains' faces pop up, and then nothing once again anymore). The audio is properly played, be it PCM generated or Redbook.

If you press start to skip, the game begins fine.

**Comment by dshadoff** [comment]
Please retest with the 20200526 release

**Comment by Left-Empty** [comment]
Totally fixed, thank you!
