### ISSUE TITLE
L-Dis (CD Game) Black screen after ship selection

### ISSUE THREAD

**Issue by Chris5523** [MiSTer-devel/TurboGrafx16_MiSTer#99]
After selecting a ship type the screen goes black and stays black.

**Comment by Chocobobobo** [comment]
After a quick check, zero problem here with the 0519 core.
![20200525_013816-screen](https://user-images.githubusercontent.com/23947970/82767630-44013900-9e29-11ea-983a-8c0a847f4444.png)

Can you send more details? What bios are you using? Timestamp of the core? Is this issue happening 100%?

**Comment by Chris5523** [comment]
Strange, core 0519 too, happening every time, just tried it again. Using the Syscard3.

**Comment by MatsuMatsu87** [comment]
I had the same issue, but overcame it by changing CD Seek to fast.
